config/routes.rb
Rails.application.routes.draw do
  resources :saved_searches, except: [:index] do
    collection do
      match :datatable, to: 'saved_searches#index', via: %i[get post]
    end
  end
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  concern :searchable, Blacklight::Routes::Searchable.new
  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog', constraints: { format: 'html' } do
    concerns :searchable
    concerns :range_searchable
    collection do
      post :update_selected_playlist
      post :assign_to_playlist
      post :assign_resources_to_list
    end
  end
  devise_for :admins
  root 'home#index'
  get '/collection', to: 'catalog#index', as: :org_collection, constraints: RestrictJsonRequest.new
  get '/playlist', to: 'home#index', as: :org_playlist
  get '/aboutus', to: 'home#index', as: :org_aboutus
  get '/robots.:format' => 'home#robots', constraints: { format: /(txt)/ }
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    invitations: 'users/invitations',
    confirmations: 'users/confirmations'
  }
  devise_scope :user do
    get '/profile', to: 'devise/registrations#edit'
  end
  post '/update_resource_column_sort/:id', to: 'organizations#update_resource_column_sort', as: 'update_resource_column_sort'
  post '/update_resource_file_column/:id', to: 'organizations#update_resource_file_column', as: 'update_resource_file_column'
  get 'forbidden', to: 'home#forbidden', as: :forbidden
  get 'notfound', to: 'home#not_found', as: :not_found
  get 'get_collections', to: 'home#featured_collections', as: :get_collections
  get 'get_playlists', to: 'home#featured_playlists', as: :get_playlists
  get 'get_resources', to: 'home#featured_resources', as: :get_resources
  get 'get_organization', to: 'home#featured_organization', as: :get_organization
  get 'record_tracking', to: 'home#record_tracking', as: :record_tracking
  get 'get_collectionwise_resources/:id', to: 'home#collection_wise_resources', as: :get_collectionwise_resources
  get 'users/add_member_row', to: 'users#add_member_row', as: :add_member_row

  namespace :admin do
    resources :users, except: %i[show] do
      put '/organization', to: 'users#organization_update'
      delete '/organization/:org_user_id', to: 'users#organization_destory', as: :organization_delete
      post '/organization', to: 'users#organization_create'

      collection do
        get '/pending', to: 'users#pending'
        get '/export_users', to: 'users#export'
      end
    end

    get '/', to: 'users#index'
  end
  get 'ohms_records', to: 'interviews/managers#index', as: :ohms_records
  get 'ohms_records/collection/ohms_records/user_assignments/:interview_id/:user_id', to: 'interviews/managers#ohms_assignments', as: :ohms_collection_records_user_assignments
  get 'my_ohms_assignment', to: 'interviews/managers#index', as: :my_ohms_assignment
  post 'my_assignment_listing', to: 'interviews/managers#listing', as: :my_assignment_listing
  post 'ohms_records', to: 'interviews/managers#create', as: :ohms_records_create
  get 'ohms_records/:id/edit', to: 'interviews/managers#edit', as: :ohms_records_edit
  get 'ohms_records/new', to: 'interviews/managers#new', as: :ohms_records_new
  get 'ohms_records/ohms_index/:id', to: 'interviews/interview_index#show', as: :ohms_index
  get 'ohms_records/ohms_index/:id/edit', to: 'interviews/interview_index#edit', as: :ohms_index_edit
  get 'ohms_records/ohms_index/new/:id', to: 'interviews/interview_index#new', as: :ohms_index_new
  get 'ohms_records/user_assignments/:interview_id/:user_id', to: 'interviews/managers#ohms_assignments', as: :ohms_records_user_assignments

  get 'ohms_configuration', to: 'interviews/managers#ohms_configuration', as: :ohms_configuration
  post 'ohms_configuration', to: 'interviews/managers#ohms_configuration_update', as: :ohms_configuration_update
  get 'ohms_records/collections', to: 'interviews/collections#index', as: :list_collections
  post 'ohms_records/collections/listing', to: 'interviews/collections#listing', as: :listing_collections

  get 'ohms_records/collection/:collection_id', to: 'interviews/collections#interviews', as: :interview_list_of_collections
  post 'ohms_records/collection/:collection_id', to: 'interviews/collections#interviews_list', as: :interview_lists_of_collections
  get 'ohms_records/collection/export/:collection_id', to: 'interviews/collections#export', as: :interview_export

  namespace :interviews do
    resources :managers do
      collection do
        post :import_metadata_xml
        post :update_column_info
        post :listing
        match :bulk_resource_list, via: %i[get post]
        post :bulk_interview_edit
      end
      member do
        get 'export.:format', to: 'managers#export', as: :export
        get 'preview', to: 'managers#preview', as: :preview
        match :sync, via: %i[get post patch]
      end
    end
    resources :transcripts, only: %i[index] do
      member do
        get 'change_sync_interval', to: 'transcripts#change_sync_interval', as: 'change_sync_interval'
        match :create, via: %i[get post]
      end
    end

    get 'interview/notes/:id.:format', to: 'notes#index', as: :list_notes
    post 'interview/notes/:id.:format', to: 'notes#create', as: :create_note
    post 'interview/note/update/:id.:format', to: 'notes#update', as: :update_note
    post 'interview/note/delete', to: 'notes#delete', as: :delete_note
    get 'ohms_interview/notes/export/:id.:format', to: 'notes#export', as: :ohms_export_note

    resources :interview_index
    get 'interview/index/new/:id', to: 'interview_index#new', as: :interview_index_new
    post 'interview/index/create/:id', to: 'interview_index#create', as: :interview_index_create
    post 'interview/index/status/:id', to: 'interview_index#status_update', as: :interview_index_status_update
    post 'interview/index/update_template/:id', to: 'interview_index#update_template', as: :interview_update_template
    get 'interview/index/index_segment_timeline/:id', to: 'interview_index#index_segment_timeline', as: :index_segment_timeline
  end

  namespace :thesaurus do
    resources :manager do
      get :export
      collection do
        match :autocomplete, via: %i[get post]
        match :assignment_management, via: %i[get post]
        match :datatable, via: %i[get post]
      end
    end
  end

  resources :users, only: %i[destroy index] do
    post '/add_new_member', to: 'users#add_new_member', as: :add_new_member
    post '/change_org_status', to: 'users#change_org_status', as: :change_org_status
    post '/change_org_role', to: 'users#change_org_role', as: :change_org_role
    get '/remove_user(/:organization_id)', to: 'users#remove_user', as: :remove_user
  end

  get 'pricing', to: 'home#pricing', as: :pricing
  get 'terms_of_service', to: 'home#terms_of_service', as: :terms_of_service
  get 'privacy_policy', to: 'home#privacy_policy', as: :privacy_policy
  # get 'contact_us', to: 'home#contact_us', as: :contact_us
  # get 'support', to: 'home#support', as: :support
  get 'about', to: 'home#about', as: :about
  get 'features', to: 'home#features', as: :features
  get 'security', to: 'home#security', as: :security
  post 'submit_request', to: 'home#submit_request', as: :submit_request
  resources :organizations, only: %i[index show update]
  get '/organization_profile', to: 'organizations#edit', as: :edit_organization
  get '/display_settings', to: 'organizations#display_settings', as: :display_settings_organization
  get :color_contrast, to: 'organizations#color_contrast', as: :color_contrast_organization
  match '/search_configuration', to: 'organizations#search_configuration', as: :search_configuration_organization, via: %i[get post]
  post '/set_layout', to: 'home#set_layout'
  scope :public_access_urls do
    match 'index', to: 'public_access_urls#index', as: 'public_access_urls', via: %i[get post]
    match 'update_info', to: 'public_access_urls#update_info', as: 'public_access_urls_update_info', via: %i[get post]
    get 'edit/:id', to: 'public_access_urls#edit', as: 'public_access_urls_edit'
    post 'update/:id', to: 'public_access_urls#update', as: 'public_access_urls_update'
  end
  resources :collection_resource_files do
    collection do
      post :data_table, to: 'collection_resource_files#index'
      post :bulk_resource_file_edit
      get :export_resource_file
      get :bulk_resource_list
    end
    get :media_thumbnail_remove
  end

  resources :organization_fields do
    collection do
      post :update_information
      post :update_index_template
      get :delete_field
      get :assignment_management
      post :create_custom_fields
      get :new_edit_custom_field
      get :index_fields_edit
    end
  end

  resources :collections do
    member do
      get 'edit/(:tab_type)', to: 'collections#edit', as: :edit_with_tab
      post :edit
      post :general_settings
      post :create_custom_fields
      get :new_edit_custom_field
      post :update_sort_fields
      get :delete_custom_meta_fields
      get :list_resources
      post :list_resources
      get :list_media
      post :list_media
      get 'collection_resources/new', to: 'collection_resources#new'
      post :import, to: 'collections#import'
      get :reset_default_tombstone_fields
    end
    collection do
      get '(/:collection_id)/export', to: 'collections#export', as: :export
      get :bulk_resource_list
      post :bulk_edit_operation
      get :fetch_bulk_edit_resource_list
      get :update_progress
      get :update_progress_files
      get :update_progress_transcripts
      get :update_progress_indexes
    end
    resources :collection_resources do
      get :add_resource_file
      post :save_resource_file
      put :update_file_name

app/controllers/interviews/collections_controller.rb
# frozen_string_literal: true

#
# Aviary is an audiovisual content publishing platform with sophisticated features for search and permissions controls.
# Copyright (C) 2019 Audio Visual Preservation Solutions, Inc.
module Interviews
  # CollectionsController
  class CollectionsController < ApplicationController
    before_action :authenticate_user!
    # GET /interview/collections
    # GET /interview/collections.json
    def index
      authorize! :manage, current_organization
      session[:interview_bulk] = [] unless request.xhr?
      @interviews = Interviews::Interview.all
      @search_columns = current_organization.interview_search_column
      @display_columns = current_organization.interview_display_column
      @collections = Collection.where(organization_id: current_organization.id)
      @users = current_organization.organization_ohms_assigned_users
    end

    def listing
      authorize! :manage, current_organization
      respond_to do |format|
        format.html
        format.json { render json: Datatables::InterviewsCollectionsDatatable.new(view_context, current_organization) }
      end
    end

    def interviews
      authorize! :manage, current_organization
      session[:interview_bulk] = [] unless request.xhr?
      @interviews = Interviews::Interview.fetch_interview_list(1, 10_000_000, [], '', { collection_id: params['collection_id'] }, {}, export: false, current_organization: current_organization)
      @search_columns = current_organization.interview_search_column
      @display_columns = current_organization.interview_display_column
      @collections = Collection.where(organization_id: current_organization.id)
      @users = current_organization.organization_ohms_assigned_users
      @collection_id = ''
      @series_id = ''
      @collection_title = ''
      @series_title = ''
      records = @interviews.try(:first)
      records.each do |record|
        @collection_id = record['collection_id_ss'] if @collection_id.blank?
        @series_id = record['series_id_ss'] if @series_id.blank?
        @collection_title = record['collection_name_ss'] if @collection_title.blank?
        @series_title = record['series_ss'] if @series_title.blank?
        if @series_title.present? && @collection_title.present? && @series_id.present? && @collection_id.present?
          break
        end
      end
      render 'interviews/managers/index'
    end

    def interviews_list
      authorize! :manage, current_organization
      organization_user = OrganizationUser.find_by(user_id: current_user.id)

      respond_to do |format|
        format.html
        format.json { render json: Datatables::InterviewsDatatable.new(view_context, current_organization, '', organization_user) }
      end
    end

    def export
      authorize! :manage, current_organization
      if params[:collection_id].present?
        InterviewBulkExportWorker.perform_in(1.second, params[:collection_id], current_user.id, current_organization.id)
      end
      redirect_to list_collections_path, notice: 'OHMS Interview XMLs are in progress and will be exported shortly. You will be notified via email once the export is complete. You do not need to stay on this page.'
    end
  end
end

app/helpers/collection_helper.rb
# Detail CollectionHelper
#
# Aviary is an audiovisual content publishing platform with sophisticated features for search and permissions controls.
# Copyright (C) 2019 Audio Visual Preservation Solutions, Inc.
module CollectionHelper
end

app/views/collections/_bulk_edit_popups.html.erb
<div class="modal fade bd-example-modal-lg bulk-edit-review-modal" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog modal-xl" role="document">

    <div class="modal-content ">

      <div class="modal-header">
        <h1 class="font-weight-bold modal-title" style="font-size: 21px;">Bulk Edit Review</h1>
      </div>
      <div class="modal-body">
        <h1 class="alert-danger font-size-21px text-center mb-20px p-2 "> Are you sure you want to
          <span id="confirm_msg_pop_bulk">change the access status of the resources listed below</span>? </h1>
        <table class="table table-hover review_resources table-sm " style="width: 100%;">
          <thead>
          <tr>
            <td  class="font-weight-bold"> ID</td>
            <td  class="font-weight-bold"> Resource Name</td>
          </tr>
          </thead>
          <tbody class="bulk-edit-review-content">
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button class="btn btn-primary bulk-edit-do-it" onclick="$('#bulk_edit_form').submit();">Apply</button>
      </div>
    </div>
  </div>
</div>
<span id="url_form_progress" data-url="<%= update_progress_collections_path %>"></span>

<div class="modal fade bd-example-modal-lg bulk-edit-modal" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <%= form_for 'bulk_edit', :html => {:class => 'bulk_edit_form', id: 'bulk_edit_form', 'data-bar' => 'baz'}, url: bulk_edit_operation_collections_path do |form| %>
        <div class="modal-header">
          <h1 class="font-weight-bold modal-title" style="font-size: 21px;">Bulk Edit</h1>
        </div>
        <div class="modal-body">
          <div class="row">

            <div class="col-12 ">
              <div class="row">
                <div class="col-12 float-left">
                  <select class="bulk_operation">
                    <option value="assign_to_collection">Assign to Collection</option>
                    <option value="assign_to_playlist">Assign to Playlist</option>
                    <option value="bulk_delete">Bulk Delete</option>
                    <option value="change_featured">Change Featured</option>
                    <option value="change_resource_index_status">Change Index Status</option>
                    <option value="change_media_file_status">Change Media File Status</option>
                    <option value="change_status">Change Status</option>
                    <option value="change_resource_transcript_status">Change Transcript Status</option>
                  </select>
                </div>
              </div>
            </div>
            <input type="hidden" name='action' value="bulk_edit_operation"/>
            <%= form.hidden_field 'type_of_bulk_operation', value: 'change_status' %>
            <div class="col-12 mt-20px">
              <div class="bulk_delete_content operation_content d-none">
                <h1 class="font-size-21px text-center"> Delete selected resources</h1>
              </div>
              <div class="change_status_content operation_content">
                <h1 class="font-size-21px text-center"> Change the access status of selected resources </h1>
                <label class="font-weight-bold">Select Status</label>
                <%= form.select 'status', CollectionResource.accesses.map { |key, _| [key.split('_').second.humanize, key] } %>
              </div>
              <div class="change_featured_content operation_content  d-none">
                <h1 class="font-size-21px text-center"> Change the featured status of selected resources</h1>
                <label class="font-weight-bold">Featured?</label>
                <%= form.select 'featured', %i[Yes No] %>
              </div>

              <div class="change_child_status_content operation_content d-none">
                <h1 class="font-size-21px text-center"> Change the access status of <span id="typeofchildaction"></span>
                  of selected resources </h1>
                <label class="font-weight-bold">Select Status</label>
                <select name="bulk_edit[child_status]">
                  <option value="access_private"> Private</option>
                  <option value="access_public"> Public</option>
                </select>
              </div>

              <div class="assign_to_collection_content operation_content  d-none">
                <h1 class="font-size-21px text-center"> Assign selected resources to a new collection</h1>
                <label class="font-weight-bold">Select Collections</label>
                <%= form.collection_select 'collections', current_organization.collections, :id, :title %>
              </div>
              <div class="assign_to_playlist_content operation_content  d-none">
                <h1 class="font-size-21px text-center"> Assign selected resources to a new playlist</h1>
                <label class="font-weight-bold">Select Playlist</label>
                <%= form.collection_select 'playlists', current_organization.playlists, :id, :name %>
              </div>
            </div>
            <div class="col-12 mt-20px">
              <span id="number_of_bulk_selected_popup" class="float-right"></span>
            </div>
          </div>
        </div>
      <% end %>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button class="btn btn-primary bulk-edit-submit" data-url="<%= fetch_bulk_edit_resource_list_collections_path %>" onclick="$('.bulk-edit-review-modal').modal()" data-dismiss="modal">Apply</button>
      </div>
    </div>
  </div>
</div>

app/views/collections/_form.html.erb
<%= simple_form_for @collection, :url => @collection.new_record? ? collections_path : collection_path, html: { novalidate: true } do |c| %>
  <div class="row org-collection-form">
    <div class="col-md-6">
      <div class="form-group banner-image small-upload small-title">
        <div class="field-title">
          <label for="">Collection Banner</label>
        </div>
        <div class="image-box">
          <div class="holder">
            <img id="banner" src="<%= @collection.new_record? ? '#' : (image_url @collection.image) %>" alt="">
          </div>
        </div>
        <div class="file-upload">
          <%= c.label @collection.new_record? ? 'Add Image' : 'Upload new image', for: 'collection_image' %>
          <%= c.input :image, as: :file, error: false, label: false, input_html: { onchange: "readURL(this, 'banner');", accept: 'image/*' } %>
        </div>
        <%= c.error :image %>
        <br>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group favicon-image small-upload small-title">
        <div class="field-title">
          <label for="">Collection Favicon</label>
        </div>
        <div class="image-box">
          <div class="holder">
            <img id="favicon" src="<%= @collection.new_record? ? '#' : (image_url @collection.favicon) %>" alt="">
          </div>
        </div>
        <div class="file-upload">
          <%= c.label @collection.new_record? ? 'Add Favicon' : 'Upload new favicon', for: 'collection_favicon' %>
          <%= c.input :favicon, as: :file, error: false, label: false, input_html: { onchange: "readURL(this, 'favicon');", accept: 'image/*' } %>
        </div>
        <%= c.error :image %>
        <br>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <div class="field-title">
          <label for="collection_title">Collection Name
            <button type="button" class="info-btn" data-content="What is your collection's name?"></button>
          </label>
        </div>
        <%= c.input :title, label: false, input_html: { class: 'form-control collection-title-field' } %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <div class="field-title">
          <label for="collection_about">About Your Collection <button type="button" class="info-btn" data-content="Tell users about your collection. This will appear in &quot;About this Collection&quot; on your collection page."></button>
          </label>
        </div>
        <%= c.input :about, label: false, input_html: { class: 'form-control' } %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <div class="field-title">
          <%= c.label 'Public ?', for: 'collection_public' %>
        </div>
        <%= c.select :is_public, [['Yes', true], ['No', false]], { prompt: 'Receive emails' }, required: true, label: false, class: 'custom-placeholder' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <div class="field-title">
          <%= c.label 'Featured ?', for: 'collection_featured' %>
        </div>
        <%= c.select :is_featured, [['Yes', true], ['No', false]], { prompt: 'Receive emails' }, required: true, label: false, class: 'custom-placeholder' %>
      </div>
    </div>
  </div>
  <% if  @collection.new_record? %>
    <div class="row pb-3 mt-3">
      <div class="col-md-12">
        <div class="form-check">
          <label class="string optional d-inline-block">
            <input type='checkbox' class="boolean optional" name='is_cloning_collection' id='collection_is_cloning_collection' />
            Clone from existing collection? <span class="icon-check"></span>
          </label>
          <button type="button" class="info-btn" data-content="By enabling this option, you can select an existing collection of yours that will be used to pre-configure the metadata fields and access policies for this new collection. Select a collection below to proceed."></button>
          <div id='collection_dd_custom' class="d-none mb-1 mt-3 form-group">
            <div class="field-title"><label class="p-0">Choose Collection</label></div>
            <%= select_tag('clone_collection', options_from_collection_for_select(current_organization.collections, 'id', 'title'), prompt: "Select a Collection.",) %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 text-right">
        <%= c.submit 'Save', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
<% end %>
<br>
<script type="text/javascript">
    var collection = new Collection();
    document.addEventListener("DOMContentLoaded", function (event) {
        collection.initialize();
    });
    $(function(e) {
        e.preventDefault;

        $('.info-btn').popover({
            html: true,
            trigger: "click",
            placement: "top"
        });

        $(document).on('click', function(e) {
            $('.info-btn').each(function() {
                if (!$(this).is(e.target) && $(this).has(e.target).length === 0 && $('.popover').has(e.target).length === 0) {
                    $(this).popover('hide');
                }
            });
        });

    });
</script>

app/views/collections/_index_collection_field_visibility.html.erb
<div class="tab">
  <div class="tab-content">
    <div class="row">
      <div class="col-12 p-5">
          <div class="row">
            <div class="col-4">
              <div class="field-title">
                <label> Index Edit Template </label>
              </div>
              <div class="form-check">
                <label class="form-check-label">
                  <input type="checkbox" name="index_default_template" class="form-check-input" value="1" <%=(@collection.index_default_template.positive? ? 'checked': '') %> >Set as default index template settings
                </label>
              </div>
              <select id='index_template' name='index_template'>
                <option value="">Select option</option>
                <%index_template_items().each_with_index do |index,key| %>
                  <option value="<%=key%>" <%=(@collection.index_template == key ? 'selected' : '')%>><%=index['name']%></option>
                <%end%>
              </select>
            </div>
          </div>

          <div class="row">
            <div class="col-12 p-5">
              <div class="holder custom_fields_container border">
                <table class="table table-hover border-0">
                  <thead class="border-top-0">
                  <tr class="">
                    <th style="width: 80% !important;"><h2>Field Name</h2></th>
                    <th style="width: 20% !important;"><h2>Display Columns</h2></th>
                  </tr>
                  </thead>
                </table>

                <table class="table table-hover" id="sort_custom_fields_table" data-url="<%= update_information_organization_fields_path(collection_id: @collection.id) %>" data-path="<%= update_sort_fields_collection_path %>">
                  <tbody id='collection_index_field_preview_org' class="ui-sortable" data-type="index_fields" data-order-custom="sort_order" data-status-columns="display">
                    <% if @index_columns_collection.present? %>
                      <% @index_columns_collection.each_with_index do |(name, props), _index| %>
                        <% label = props['display_name'] %>

                        <tr class="<%= name %>" data-field="<%= name %>" data-label="<%= label %>" data-is-required-field="<%= props['required'] %>">
                          <td width="80%">
                            <i class="fa fa-ellipsis-v handle mx-2" style="color: lightgrey;cursor: move;"></i>
                            <span data-toggle="tooltip" data-placement="top" title="" aria-hidden="true" data-original-title="<%= name %>">
                              <%= label %>
                            </span>
                            <% if props['required'].to_s.to_boolean? %>
                              <i class="fa fa-asterisk color-grey font-size-8px" data-toggle="tooltip" data-placement="top" title="" aria-hidden="true" data-original-title="This is a required field and cannot be reordered or disabled."></i>
                            <% end %>
                            <small class="mt-2 form-text font-size-12px text-muted d-inline">
                              <%= name %>
                            </small>

                          </td>
                          <td width="10%">
                            <label class="toggle-switch ml-3">
                              <%= check_box_tag 'display_' + name, props['display'], props['display'].to_s.to_boolean?,
                                disabled: props['required'], class: "display toggle-switch__input template-data-is-facetable template-data-field-is-facetable" %>

                                <span class="toggle-switch__slider"></span>
                            </label>
                          </td>
                        </tr>
                      <% end %>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/collections/add_field_visibility.html.erb
<div id="wrapper">
  <main id="main" role="main">
    <div class="org-metadata">
      <div class="container">
        <div class="row">


          <div class="col-md-8 offset-md-2">
            <table class="table pb-0 mb-0">

            </table>
            <div class="holder custom_fields_container">
              <%= render partial: "custom_fields_table", locals: { latest_field_label: nil } %>
            </div>
            <div class="row bottom">
              <div class="col-md-6">
                <%= link_to "Add Custom Fields", new_edit_custom_field_collection_path(@collection), class: "btn btn-primary edit-custom-field-button edit-custom-field-button-new-custom-spec", data: {method_type: "new"} %>
                <br>
                <br>
                <br>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>
<div id="show_custom_fields_add"></div>
<div id="show_custom_vocabulary_modal"></div>

app/views/collections/list_media.html.erb
<div id="main_container" class="container-fluid">
  <div class="main_contain">
    <main>
      <div class="heading-holder table-head mb-4 text-headline jumbotron">
        <div class="row">
          <div class="col-md-7"><h1><%= @collection.title %> </h1></div>
            <div class="col-md-5 ">
              <%= render partial: 'collection_resource_files/collection_resource_files_buttons' %>
            </div>
          </div>
        </div>
      </div>
      <div class="data-table">
        <%= content_tag :table, role: :datatable, class: ['table', 'table-striped','table-bordered'], id: 'collection_media_datatable', data: { url: list_media_collection_path(@collection, format: :json) } do %>
          <%= render partial: 'collection_resource_files/files_listing_table', locals: {table_called_from: 'media_files_index', columns_details: JSON.parse(current_organization.resource_file_display_column)['columns_status'], organization_id: current_organization.id } %>
        <% end %>
      </div>
    </main>
  </div>
</div>
<span id="url_form_progress" data-url="<%= update_progress_files_collections_path %>"></span>
<%= render partial: 'collection_resource_files/manage_column', locals: { columns_details: JSON.parse(current_organization.resource_file_display_column)['columns_status'], search_columns_details: JSON.parse(current_organization.resource_file_search_column), organization_id: current_organization.id } %>
<%= render partial: 'collection_resource_files/bulk_edit_resource_file' %>
<%= render partial: 'collection_resource_files/import_csv' %>
<script type="text/javascript">
    var collection_media_table = new CollectionMediaTable();
    $(function () {

        collection_media_table.initialize('<%== current_organization.resource_file_display_column %>', '<%= session[:resource_file_list_bulk_edit] %>');
    });
</script>