config/routes.rb
Rails.application.routes.draw do
  resources :saved_searches, except: [:index] do
    collection do
      match :datatable, to: 'saved_searches#index', via: %i[get post]
    end
  end
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  concern :searchable, Blacklight::Routes::Searchable.new
  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog', constraints: { format: 'html' } do
    concerns :searchable
    concerns :range_searchable
    collection do
      post :update_selected_playlist
      post :assign_to_playlist
      post :assign_resources_to_list
    end
  end
  devise_for :admins
  root 'home#index'
  get '/collection', to: 'catalog#index', as: :org_collection, constraints: RestrictJsonRequest.new
  get '/playlist', to: 'home#index', as: :org_playlist
  get '/aboutus', to: 'home#index', as: :org_aboutus
  get '/robots.:format' => 'home#robots', constraints: { format: /(txt)/ }
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    invitations: 'users/invitations',
    confirmations: 'users/confirmations'
  }
  devise_scope :user do
    get '/profile', to: 'devise/registrations#edit'
  end
  post '/update_resource_column_sort/:id', to: 'organizations#update_resource_column_sort', as: 'update_resource_column_sort'
  post '/update_resource_file_column/:id', to: 'organizations#update_resource_file_column', as: 'update_resource_file_column'
  get 'forbidden', to: 'home#forbidden', as: :forbidden
  get 'notfound', to: 'home#not_found', as: :not_found
  get 'get_collections', to: 'home#featured_collections', as: :get_collections
  get 'get_playlists', to: 'home#featured_playlists', as: :get_playlists
  get 'get_resources', to: 'home#featured_resources', as: :get_resources
  get 'get_organization', to: 'home#featured_organization', as: :get_organization
  get 'record_tracking', to: 'home#record_tracking', as: :record_tracking
  get 'get_collectionwise_resources/:id', to: 'home#collection_wise_resources', as: :get_collectionwise_resources
  get 'users/add_member_row', to: 'users#add_member_row', as: :add_member_row

  namespace :admin do
    resources :users, except: %i[show] do
      put '/organization', to: 'users#organization_update'
      delete '/organization/:org_user_id', to: 'users#organization_destory', as: :organization_delete
      post '/organization', to: 'users#organization_create'

      collection do
        get '/pending', to: 'users#pending'
        get '/export_users', to: 'users#export'
      end
    end

    get '/', to: 'users#index'
  end
  get 'ohms_records', to: 'interviews/managers#index', as: :ohms_records
  get 'ohms_records/collection/ohms_records/user_assignments/:interview_id/:user_id', to: 'interviews/managers#ohms_assignments', as: :ohms_collection_records_user_assignments
  get 'my_ohms_assignment', to: 'interviews/managers#index', as: :my_ohms_assignment
  post 'my_assignment_listing', to: 'interviews/managers#listing', as: :my_assignment_listing
  post 'ohms_records', to: 'interviews/managers#create', as: :ohms_records_create
  get 'ohms_records/:id/edit', to: 'interviews/managers#edit', as: :ohms_records_edit
  get 'ohms_records/new', to: 'interviews/managers#new', as: :ohms_records_new
  get 'ohms_records/ohms_index/:id', to: 'interviews/interview_index#show', as: :ohms_index
  get 'ohms_records/ohms_index/:id/edit', to: 'interviews/interview_index#edit', as: :ohms_index_edit
  get 'ohms_records/ohms_index/new/:id', to: 'interviews/interview_index#new', as: :ohms_index_new
  get 'ohms_records/user_assignments/:interview_id/:user_id', to: 'interviews/managers#ohms_assignments', as: :ohms_records_user_assignments

  get 'ohms_configuration', to: 'interviews/managers#ohms_configuration', as: :ohms_configuration
  post 'ohms_configuration', to: 'interviews/managers#ohms_configuration_update', as: :ohms_configuration_update
  get 'ohms_records/collections', to: 'interviews/collections#index', as: :list_collections
  post 'ohms_records/collections/listing', to: 'interviews/collections#listing', as: :listing_collections

  get 'ohms_records/collection/:collection_id', to: 'interviews/collections#interviews', as: :interview_list_of_collections
  post 'ohms_records/collection/:collection_id', to: 'interviews/collections#interviews_list', as: :interview_lists_of_collections
  get 'ohms_records/collection/export/:collection_id', to: 'interviews/collections#export', as: :interview_export

  namespace :interviews do
    resources :managers do
      collection do
        post :import_metadata_xml
        post :update_column_info
        post :listing
        match :bulk_resource_list, via: %i[get post]
        post :bulk_interview_edit
      end
      member do
        get 'export.:format', to: 'managers#export', as: :export
        get 'preview', to: 'managers#preview', as: :preview
        match :sync, via: %i[get post patch]
      end
    end
    resources :transcripts, only: %i[index] do
      member do
        get 'change_sync_interval', to: 'transcripts#change_sync_interval', as: 'change_sync_interval'
        match :create, via: %i[get post]
      end
    end

    get 'interview/notes/:id.:format', to: 'notes#index', as: :list_notes
    post 'interview/notes/:id.:format', to: 'notes#create', as: :create_note
    post 'interview/note/update/:id.:format', to: 'notes#update', as: :update_note
    post 'interview/note/delete', to: 'notes#delete', as: :delete_note
    get 'ohms_interview/notes/export/:id.:format', to: 'notes#export', as: :ohms_export_note

    resources :interview_index
    get 'interview/index/new/:id', to: 'interview_index#new', as: :interview_index_new
    post 'interview/index/create/:id', to: 'interview_index#create', as: :interview_index_create
    post 'interview/index/status/:id', to: 'interview_index#status_update', as: :interview_index_status_update
    post 'interview/index/update_template/:id', to: 'interview_index#update_template', as: :interview_update_template
    get 'interview/index/index_segment_timeline/:id', to: 'interview_index#index_segment_timeline', as: :index_segment_timeline
  end

  namespace :thesaurus do
    resources :manager do
      get :export
      collection do
        match :autocomplete, via: %i[get post]
        match :assignment_management, via: %i[get post]
        match :datatable, via: %i[get post]
      end
    end
  end

  resources :users, only: %i[destroy index] do
    post '/add_new_member', to: 'users#add_new_member', as: :add_new_member
    post '/change_org_status', to: 'users#change_org_status', as: :change_org_status
    post '/change_org_role', to: 'users#change_org_role', as: :change_org_role
    get '/remove_user(/:organization_id)', to: 'users#remove_user', as: :remove_user
  end

  get 'pricing', to: 'home#pricing', as: :pricing
  get 'terms_of_service', to: 'home#terms_of_service', as: :terms_of_service
  get 'privacy_policy', to: 'home#privacy_policy', as: :privacy_policy
  # get 'contact_us', to: 'home#contact_us', as: :contact_us
  # get 'support', to: 'home#support', as: :support
  get 'about', to: 'home#about', as: :about
  get 'features', to: 'home#features', as: :features
  get 'security', to: 'home#security', as: :security
  post 'submit_request', to: 'home#submit_request', as: :submit_request
  resources :organizations, only: %i[index show update]
  get '/organization_profile', to: 'organizations#edit', as: :edit_organization
  get '/display_settings', to: 'organizations#display_settings', as: :display_settings_organization
  get :color_contrast, to: 'organizations#color_contrast', as: :color_contrast_organization
  match '/search_configuration', to: 'organizations#search_configuration', as: :search_configuration_organization, via: %i[get post]
  post '/set_layout', to: 'home#set_layout'
  scope :public_access_urls do
    match 'index', to: 'public_access_urls#index', as: 'public_access_urls', via: %i[get post]
    match 'update_info', to: 'public_access_urls#update_info', as: 'public_access_urls_update_info', via: %i[get post]
    get 'edit/:id', to: 'public_access_urls#edit', as: 'public_access_urls_edit'
    post 'update/:id', to: 'public_access_urls#update', as: 'public_access_urls_update'
  end
  resources :collection_resource_files do
    collection do
      post :data_table, to: 'collection_resource_files#index'
      post :bulk_resource_file_edit
      get :export_resource_file
      get :bulk_resource_list
    end
    get :media_thumbnail_remove
  end

  resources :organization_fields do
    collection do
      post :update_information
      post :update_index_template
      get :delete_field
      get :assignment_management
      post :create_custom_fields
      get :new_edit_custom_field
      get :index_fields_edit
    end
  end

  resources :collections do
    member do
      get 'edit/(:tab_type)', to: 'collections#edit', as: :edit_with_tab
      post :edit
      post :general_settings
      post :create_custom_fields
      get :new_edit_custom_field
      post :update_sort_fields
      get :delete_custom_meta_fields
      get :list_resources
      post :list_resources
      get :list_media
      post :list_media
      get 'collection_resources/new', to: 'collection_resources#new'
      post :import, to: 'collections#import'
      get :reset_default_tombstone_fields
    end
    collection do
      get '(/:collection_id)/export', to: 'collections#export', as: :export
      get :bulk_resource_list
      post :bulk_edit_operation
      get :fetch_bulk_edit_resource_list
      get :update_progress
      get :update_progress_files
      get :update_progress_transcripts
      get :update_progress_indexes
    end
    resources :collection_resources do
      get :add_resource_file
      post :save_resource_file
      put :update_file_name

app/views/home/_collections_home.html.erb
<% if featured_collections.present? %>
  <h3>Featured Collections</h3>
  <div class="home-featured-collections">
    <% featured_collections.each do |collection| %>
      <div class="item">
        <%= link_to collection_url(collection, host: Utilities::AviaryDomainHandler.subdomain_handler(collection.organization)) do %>
          <div class="image" style="<%= url_image(collection.collection_card_image)%>; background-position: center;">
          </div>

          <div class="resource-detail-data">
            <div class="col-12 organization">
              <div class="main-hold">
                <div class="img-hold">
                  <%= image_tag(collection.organization.favicon.present? ? collection.organization.favicon(:small) : collection.organization.logo_image(:medium), alt: collection.organization.name) %>
                </div>
              </div>
              <div class="details">
                <span class="title"><%= collection.title %></span>
                <span class="collection-title"><%= collection.organization.name %></span>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/home/_featured_organizations_home.html.erb
<% if featured_organizations.present? %>
  <div class="collection-portal-members">
    <div class="container">
      <div class="collection-resources-head">
        <h3>Featured Aviary Sites</h3>
        <a href="<%= organizations_path %>" class="view-all-sites">More Aviary Sites</a>
      </div>
      <div class="row">
        <% featured_organizations.each do |organization| %>
          <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
            <div class="box portal">
              <%= link_to root_url(host: Utilities::AviaryDomainHandler.subdomain_handler(organization)), target: "_blank" do %>
                <div class="image " style="<%= url_image(organization.banner_image.url(:small))%>; background-position: center;min-height: 120px;">
                </div>
                <div class="collection-details">
                  <div class="img-hold">
                    <%= image_tag(organization.favicon.present? ? organization.favicon(:small) : organization.logo_image(:medium), alt: organization.name) %>
                  </div>
                  <h4 class="reso-title"><%= organization.name %></h4>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/home/_organization_home.html.erb
<% if ['/aboutus', '/'].include?(request.fullpath) %>
  <%= render partial: 'home/home_banner', locals: { banner_type: current_organization.banner_type,
                                                    display_banner: current_organization.display_banner,
                                                    banner_image: current_organization.banner_image,
                                                    banner_slider_resources: current_organization.banner_slider_resources,
                                                    panel_color: current_organization.search_panel_bg_color.present? ? current_organization.search_panel_bg_color : '#f05d1f',
                                                    banner_title_text: current_organization.banner_title_text,
                                                    title_font_family: current_organization.title_font_family,
                                                    title_font_size: current_organization.title_font_size,
                                                    title_font_color: current_organization.title_font_color,
                                                    banner_view_from: 'organization'
  } %>
<% end %>
<% if request.fullpath == '/aboutus' || (request.fullpath == '/' && current_organization.default_tab_selection == 'about') || current_organization.default_tab_selection.blank? %>
  <div class="container">
    <div class="org-about-panel">
      <p><%== description current_organization.description %></p>
    </div>
  </div>
<% elsif request.fullpath == '/collection' || (request.fullpath == '/' && current_organization.default_tab_selection == 'collections') %>
  <div class="all-resources container home-index-view">
    <div id="collections_home" data-path="<%= get_collections_path %>">
    </div>
  </div>
<% elsif request.fullpath == '/playlist' || (request.fullpath == '/' && current_organization.default_tab_selection == 'playlists') %>
  <div class="all-resources container home-index-view">
    <div id="playlists_home" data-path="<%= get_playlists_path %>">
    </div>
  </div>
<% end %>

<br/>
<div class="modal fade collection-detail-modal" id="detailDisplayModal" tabindex="-1" role="dialog" aria-labelledby="detailDisplayModal" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <div class="row">
          <div class="col-md-12">
            <div class="image-holder collection_image_holder d-none" style="">
            </div>
            <div class="details">
              <div class="org-icon">
                <div class="hold">
                  <img class="collection-org-logo" src="">
                </div>
              </div>
              <div class="text">
                <strong><a style="color: #333;" target="_blank" class="collection_collection_title" href=""></a></strong>
                <span class="collection_org_title"></span>
              </div>
              <a href="#" target="_blank" class="btn-link collection_search_collection">Browse</a>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="list list-collection-info">
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    let colelction_resources = new CollectionResource();
    let homePage = new HomePage();
    document.addEventListener("DOMContentLoaded", function (event) {
        homePage.orgInitialize();
        colelction_resources.loadCollectionwiseResources();
    });
</script>

app/views/home/_playlists_home_inner.html.erb
<% if featured_playlists.present? %>
  <div class="home-featured-collections playlist_home_cont row">
    <% featured_playlists.includes([:organization]).each do |playlist| %>
      <div class="col-md-4">
        <div class="box <%= 'featured' if playlist.is_featured %>">
          <a href="<%= playlist_show_path(playlist) %>">
            <div class="image" style="background-size:cover;background-image: url(<%= playlist.thumbnail.url(:small) %>); background-position: center;">
            </div>
          </a>
          <div class="resource-detail-data">
            <div class="col-12 organization">
              <div class="main-hold">
                <div class="img-hold">
                  <%= image_tag(playlist.organization.favicon.present? ? playlist.organization.favicon(:small) : playlist.organization.logo_image(:medium), alt: playlist.organization.name) %>
                </div>
              </div>
              <div class="details">
                <%= link_to playlist_show_path(playlist) do %>
                  <span class="title"><%= playlist.name %></span>
                <% end %>
                <span class="description_collection">
                    <%= strip_tags(playlist.description).to_s.truncate(60, omission: '...', :separator => ' ') %></span>
                <a data-toggle="modal" class='show_hide_description info-btn' data-type="View Playlist" data-id="description_<%= playlist.id %>" data-collection-img='<%= url_image(playlist.thumbnail.url(:small)) %>'
                   data-collection-title="<%= playlist.name %>" data-org-logo="<%= playlist.organization.logo_image.url(:medium) %>" data-collection-path="<%= playlist_show_path(playlist) %>" data-org-title="<%= playlist.organization.name %>"
                   data-collection-search="<%= playlist_show_path(playlist) %>">
                </a>
                <div class="description description_<%= playlist.id %> d-none">
                  <ul>
                    <li><strong>Description</strong>
                      <div><%= playlist.description.try(:html_safe) %></div>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="browse-org">
            <a target="_blank" class="float-left"
               href="<%= search_catalog_path({ f: { playlist_ims: [playlist.id] }, indexes: [], keywords: [],
                                                    op: [], resource_description: [], search_field: 'advanced',
                                                    search_type: 'simple', title_text: '', transcript: [],
                                                    type_of_search: ['simple'] }) %>">
              Search Playlist <i class="fa fa-external-link"></i>
            </a>

            <a target="_blank" href="<%= playlist_show_path(playlist) %>"> View Playlist <i class="fa fa-external-link"></i></a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/home/_resources_home.html.erb
<% if featured_resources.present? %>

  <div class="collection-featured-resources">
    <div class="collection-resources-head">
      <h3><%= featured ? 'Featured' : 'All' %> Content</h3>
    </div>
    <div class="row">
      <% featured_resources.each_with_index do |collection_resource, index| %>
        <% break if index > 2 %>
        <%= render partial: 'home/resources/resources_row', locals: { resource: collection_resource, featured: false } %>
      <% end %>
    </div>
    <% if @collection.present? %>
      <div class="collection-featured-head">
        <div class="collection-resources-head">
          <h3>Featured Collection</h3>
          <!--          <button>More Collection</button>-->
        </div>
        <div class="d-flex">
          <div class="organization-detail">
            <div class="img-hold">
              <%= image_tag(@collection.organization.favicon.present? ? @collection.organization.favicon(:small) : @collection.organization.logo_image(:medium), alt: @collection.organization.name) %>
            </div>
            <div>
              <div class="organization-name"><%= @collection.organization.name %></div>
              <div class="collection-name"><%= @collection.title %></div>
              <%= link_to collection_url(@collection, host: Utilities::AviaryDomainHandler.subdomain_handler(@collection.organization)), target: "_blank" do %>
                See Collection
              <% end %>

            </div>
          </div>
          <div class="resources-list">
            <div class="owl-carousel owl-theme collection_resource_carousel">
              <% @collection_resources.each do |collection_resource| %>
                <% file = collection_resource.collection_resource_files.order_file.first %>
                <% resource_url = collection_collection_resource_details_url(collection_resource.collection, collection_resource, host: Utilities::AviaryDomainHandler.subdomain_handler(collection_resource.collection.organization)) %>
                <div class="item">
                  <div class="box small">
                    <%= link_to resource_url, target: "_blank" do %>
                      <div class="image " style="background: url(<%= file.thumbnail_image %>); background-size:cover;background-position: center;min-height: 120px;">
                        <time><%= !collection_resource.custom_field_value('duration').blank? ? time_to_duration(collection_resource.custom_field_value('duration').first['value']) : '00:00:00' %></time>
                      </div>
                      <div class="collection-details">
                        <h4 class="reso-title"><%= collection_resource.title %></h4>
                      </div>
                    <% end %>
                  </div>
                </div>
              <% end %>


            </div>
          </div>
        </div>
      </div>
    <% end %>
    <div class="row">
      <% featured_resources.each_with_index do |collection_resource, index| %>
        <% next if index < 3 %>
        <%= render partial: 'home/resources/resources_row', locals: { resource: collection_resource, featured: false } %>
      <% end %>
    </div>

  </div>
<% end %>

app/views/home/_resources_home_inner.html.erb
<% if featured_resources.present? %>
  <% from_lazy_load = false unless from_lazy_load.present? %>
  <% unless from_lazy_load %>
    <div class="home-featured-resources row" id="landing-main">
  <% end %>
  <% featured_resources.each do |collection_resource| %>
    <%= render partial: 'home/resources/resources_row', locals: { resource: collection_resource, featured: collection_resource.is_featured } %>
  <% end %>
  <% unless from_lazy_load %>
    </div>
  <% end %>
<% end %>

<% if collection_wise_resources.present? %>
  <div class="collection_wise_resources">
    <% collection_wise_resources.each do |collection_resource| %>
      <% if collection_resource.collection_resources.size > 0 %>
        <div id="collection_resource<%= collection_resource[:id] %>" data-id="<%= collection_resource[:id] %>" data-path="<%= get_collectionwise_resources_path(collection_resource[:id]) %>">
          <% if collection_resource[:resources].present? %>
            <div class="head"><h3>
              <a href="<%= collection_path(collection_resource[:id]) %>" style="color: #333;" target="_blank"><%= collection_resource[:title] %></a>
            </h3></div>
            <div class="row">
              <% collection_resource[:resources].each do |collection_resource| %>
                <%= render partial: 'home/resources/resources_row', locals: { resource: collection_resource, featured: collection_resource.is_featured } %>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/home/about.html.erb
<div class="about-main-page">
  <div class="head">
    <h1>
      <% title 'About Us' %>Welcome to Aviary!</h1>
    <p><%= description 'Aviary is a new hosted platform that allows users to easily discover and navigate audiovisual content.
      Whether you are a researcher trying to find specific audiovisual resources for your work, an organization trying
      to enhance discoverability of your collections, or a user who wants to watch content online, Aviary offers
      advanced tools to display, describe, and search audio and video.' %></p>
  </div>
  <div class="image">
    <div class="container">
      <h2>The Aviary Ecosystem</h2>
      <%= image_tag("https://#{ENV['S3_HOST_CDN']}/public/about-image.png") %>
    </div>
  </div>
  <div class="annotations">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="image-holder">
            <%= image_tag("https://#{ENV['S3_HOST_CDN']}/public/annotations-image.png") %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="text">
            <h3>Annotations</h3>
            <p>Available in our next release, user-based, fully searchable annotations <br> will be available
              for all Aviary elements.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="users">
    <div class="container">
      <h2>The Aviary Users</h2>
      <article>
        <div class="row">
          <div class="col-md-6">
            <div class="img-holder">
              <%= image_tag("https://#{ENV['S3_HOST_CDN']}/public/pub-user.png") %>
            </div>
          </div>
          <div class="col-md-6">
            <div class="text">
              <h3>Public Users</h3>
              <p>Searching content in Aviary is free of charge! Any content made public in Aviary
                is fully searchable in the platform. As a public user, you can search organizations,
                collections, resources, and even transcripts and indexes, as well as navigate content
                using the different visualization tools.</p>
              <p>Ready to start searching?</p>
              <a href="<%= search_catalog_url(q: '', search_field: 'all_fields', utf8: '✓') %>" class="btn btn-primary">Search
                Now!</a>
            </div>
          </div>
        </div>
      </article>
      <article>
        <div class="row">
          <div class="col-md-6">
            <div class="text">
              <h3>Registered Users</h3>
              <p>As a registered user, you can enjoy all the search features offered to
                public users. Additionally you have the ability to request access to private
                content directly from the content administrators. In future releases, registered
                users will be able to annotate content at any level (collection, resource, media, and
                transcript/index).</p>
              <% unless user_signed_in? %>
                <p>Ready to register?</p>
                <a href="javascript://" data-toggle="modal" data-target="#signupmodal" class="btn btn-primary">Join
                  Now!</a>
              <% end %>
            </div>
          </div>
          <div class="col-md-6">
            <div class="img-holder two">
              <%= image_tag("https://#{ENV['S3_HOST_CDN']}/public/reg-user.png") %>
            </div>

          </div>
        </div>
      </article>
      <article>
        <div class="row">
          <div class="col-md-6">
            <div class="img-holder three">
              <%= image_tag("https://#{ENV['S3_HOST_CDN']}/public/org-about.png") %>
            </div>
          </div>
          <div class="col-md-6">
            <div class="text">
              <h3>Organizations</h3>
              <p>Take full advantage of enhanced discoverability for your audiovisual collections!
                Putting your content in Aviary is easy thanks to our integrations with Youtube, Vimeo,
                Avalon, SoundCloud, and bulk import functionalities. We offer different plans to fit
                your needs.</p>

              <p>Ready to put your content in Aviary?</p>
              <a href="<%= pricing_path %>" class="btn btn-primary">See Available Plans!</a>

            </div>
          </div>
        </div>
      </article>
    </div>
  </div>
  <div class="plans-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="jumbotron">
            <h1>More about Aviary?</h1>
            <p>Check Aviary's features to learn how our platform can help your organization provide enhanced access to
              your audiovisual collections.</p>
            <a class="btn btn-info btn-lg" href="<%= features_path %>" role="button">View Features</a>
          </div>
        </div>
        <div class="col-md-6">
          <div class="jumbotron">
            <h1>Questions?</h1>
            <p>Still have questions about pricing? Get in touch!</p>
            <a class="btn btn-info btn-lg" href="<%= contact_us_path %>" role="button">Contact Us</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/forbidden.html.erb
<%= render template: 'home/index' %>
<div class="modal fade" id="access_denied_popup" tabindex="-1" role="dialog" aria-labelledby="access_denied_popup" aria-hidden="true">
  <div class="modal-md modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title h4">Access Denied</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="font-weight-bold mb-20px">We are sorry! You don't have access to this content. Please contact your organization administrator for more
        details.
        </div>
        <% unless user_signed_in? %>
        <div>
          <%= form_for resource, as: resource_name, url: session_path(resource_name), validate: true do |f| %>
            <%= f.email_field :email, autofocus: true, required: true, class: 'form-control mb-10px', placeholder: 'Email Address' %>

            <%= f.password_field :password, autocomplete: 'off', class: 'form-control', placeholder: 'Password' %>

            <div class="row mt-10px">
              <div class="col-md-12">
                <a href="#" data-toggle="modal" data-target="#forgot_password_modal" data-dismiss="modal" class="forgot ml-3">Forgot
                  Password</a>
              </div>
            </div>
            <div class="row mt-10px">
              <div class="col-md-12">
                <%= f.submit 'Sign in', class: 'btn btn-lg btn-primary btn-block checking' %>
              </div>
            </div>

          <% end %>
          <div class="mt-10px">Don't have an account?
            <a href="javascript://" class="sign_up_link">Join now!</a>
          </div>
        </div>
          <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    $('#access_denied_popup').modal({
        backdrop: 'static'
    });
</script>

app/views/home/index.html.erb
<%= render partial: 'layouts/loading_skeleton', locals: {count: 3} %>
<%= render 'home/organization_home' %>