config/routes.rb
Rails.application.routes.draw do
  resources :saved_searches, except: [:index] do
    collection do
      match :datatable, to: 'saved_searches#index', via: %i[get post]
    end
  end
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  concern :searchable, Blacklight::Routes::Searchable.new
  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog', constraints: { format: 'html' } do
    concerns :searchable
    concerns :range_searchable
    collection do
      post :update_selected_playlist
      post :assign_to_playlist
      post :assign_resources_to_list
    end
  end
  devise_for :admins
  root 'home#index'
  get '/collection', to: 'catalog#index', as: :org_collection, constraints: RestrictJsonRequest.new
  get '/playlist', to: 'home#index', as: :org_playlist
  get '/aboutus', to: 'home#index', as: :org_aboutus
  get '/robots.:format' => 'home#robots', constraints: { format: /(txt)/ }
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    invitations: 'users/invitations',
    confirmations: 'users/confirmations'
  }
  devise_scope :user do
    get '/profile', to: 'devise/registrations#edit'
  end
  post '/update_resource_column_sort/:id', to: 'organizations#update_resource_column_sort', as: 'update_resource_column_sort'
  post '/update_resource_file_column/:id', to: 'organizations#update_resource_file_column', as: 'update_resource_file_column'
  get 'forbidden', to: 'home#forbidden', as: :forbidden
  get 'notfound', to: 'home#not_found', as: :not_found
  get 'get_collections', to: 'home#featured_collections', as: :get_collections
  get 'get_playlists', to: 'home#featured_playlists', as: :get_playlists
  get 'get_resources', to: 'home#featured_resources', as: :get_resources
  get 'get_organization', to: 'home#featured_organization', as: :get_organization
  get 'record_tracking', to: 'home#record_tracking', as: :record_tracking
  get 'get_collectionwise_resources/:id', to: 'home#collection_wise_resources', as: :get_collectionwise_resources
  get 'users/add_member_row', to: 'users#add_member_row', as: :add_member_row

  namespace :admin do
    resources :users, except: %i[show] do
      put '/organization', to: 'users#organization_update'
      delete '/organization/:org_user_id', to: 'users#organization_destory', as: :organization_delete
      post '/organization', to: 'users#organization_create'

      collection do
        get '/pending', to: 'users#pending'
        get '/export_users', to: 'users#export'
      end
    end

    get '/', to: 'users#index'
  end
  get 'ohms_records', to: 'interviews/managers#index', as: :ohms_records
  get 'ohms_records/collection/ohms_records/user_assignments/:interview_id/:user_id', to: 'interviews/managers#ohms_assignments', as: :ohms_collection_records_user_assignments
  get 'my_ohms_assignment', to: 'interviews/managers#index', as: :my_ohms_assignment
  post 'my_assignment_listing', to: 'interviews/managers#listing', as: :my_assignment_listing
  post 'ohms_records', to: 'interviews/managers#create', as: :ohms_records_create
  get 'ohms_records/:id/edit', to: 'interviews/managers#edit', as: :ohms_records_edit
  get 'ohms_records/new', to: 'interviews/managers#new', as: :ohms_records_new
  get 'ohms_records/ohms_index/:id', to: 'interviews/interview_index#show', as: :ohms_index
  get 'ohms_records/ohms_index/:id/edit', to: 'interviews/interview_index#edit', as: :ohms_index_edit
  get 'ohms_records/ohms_index/new/:id', to: 'interviews/interview_index#new', as: :ohms_index_new
  get 'ohms_records/user_assignments/:interview_id/:user_id', to: 'interviews/managers#ohms_assignments', as: :ohms_records_user_assignments

  get 'ohms_configuration', to: 'interviews/managers#ohms_configuration', as: :ohms_configuration
  post 'ohms_configuration', to: 'interviews/managers#ohms_configuration_update', as: :ohms_configuration_update
  get 'ohms_records/collections', to: 'interviews/collections#index', as: :list_collections
  post 'ohms_records/collections/listing', to: 'interviews/collections#listing', as: :listing_collections

  get 'ohms_records/collection/:collection_id', to: 'interviews/collections#interviews', as: :interview_list_of_collections
  post 'ohms_records/collection/:collection_id', to: 'interviews/collections#interviews_list', as: :interview_lists_of_collections
  get 'ohms_records/collection/export/:collection_id', to: 'interviews/collections#export', as: :interview_export

  namespace :interviews do
    resources :managers do
      collection do
        post :import_metadata_xml
        post :update_column_info
        post :listing
        match :bulk_resource_list, via: %i[get post]
        post :bulk_interview_edit
      end
      member do
        get 'export.:format', to: 'managers#export', as: :export
        get 'preview', to: 'managers#preview', as: :preview
        match :sync, via: %i[get post patch]
      end
    end
    resources :transcripts, only: %i[index] do
      member do
        get 'change_sync_interval', to: 'transcripts#change_sync_interval', as: 'change_sync_interval'
        match :create, via: %i[get post]
      end
    end

    get 'interview/notes/:id.:format', to: 'notes#index', as: :list_notes
    post 'interview/notes/:id.:format', to: 'notes#create', as: :create_note
    post 'interview/note/update/:id.:format', to: 'notes#update', as: :update_note
    post 'interview/note/delete', to: 'notes#delete', as: :delete_note
    get 'ohms_interview/notes/export/:id.:format', to: 'notes#export', as: :ohms_export_note

    resources :interview_index
    get 'interview/index/new/:id', to: 'interview_index#new', as: :interview_index_new
    post 'interview/index/create/:id', to: 'interview_index#create', as: :interview_index_create
    post 'interview/index/status/:id', to: 'interview_index#status_update', as: :interview_index_status_update
    post 'interview/index/update_template/:id', to: 'interview_index#update_template', as: :interview_update_template
    get 'interview/index/index_segment_timeline/:id', to: 'interview_index#index_segment_timeline', as: :index_segment_timeline
  end

  namespace :thesaurus do
    resources :manager do
      get :export
      collection do
        match :autocomplete, via: %i[get post]
        match :assignment_management, via: %i[get post]
        match :datatable, via: %i[get post]
      end
    end
  end

  resources :users, only: %i[destroy index] do
    post '/add_new_member', to: 'users#add_new_member', as: :add_new_member
    post '/change_org_status', to: 'users#change_org_status', as: :change_org_status
    post '/change_org_role', to: 'users#change_org_role', as: :change_org_role
    get '/remove_user(/:organization_id)', to: 'users#remove_user', as: :remove_user
  end

  get 'pricing', to: 'home#pricing', as: :pricing
  get 'terms_of_service', to: 'home#terms_of_service', as: :terms_of_service
  get 'privacy_policy', to: 'home#privacy_policy', as: :privacy_policy
  # get 'contact_us', to: 'home#contact_us', as: :contact_us
  # get 'support', to: 'home#support', as: :support
  get 'about', to: 'home#about', as: :about
  get 'features', to: 'home#features', as: :features
  get 'security', to: 'home#security', as: :security
  post 'submit_request', to: 'home#submit_request', as: :submit_request
  resources :organizations, only: %i[index show update]
  get '/organization_profile', to: 'organizations#edit', as: :edit_organization
  get '/display_settings', to: 'organizations#display_settings', as: :display_settings_organization
  get :color_contrast, to: 'organizations#color_contrast', as: :color_contrast_organization
  match '/search_configuration', to: 'organizations#search_configuration', as: :search_configuration_organization, via: %i[get post]
  post '/set_layout', to: 'home#set_layout'
  scope :public_access_urls do
    match 'index', to: 'public_access_urls#index', as: 'public_access_urls', via: %i[get post]
    match 'update_info', to: 'public_access_urls#update_info', as: 'public_access_urls_update_info', via: %i[get post]
    get 'edit/:id', to: 'public_access_urls#edit', as: 'public_access_urls_edit'
    post 'update/:id', to: 'public_access_urls#update', as: 'public_access_urls_update'
  end
  resources :collection_resource_files do
    collection do
      post :data_table, to: 'collection_resource_files#index'
      post :bulk_resource_file_edit
      get :export_resource_file
      get :bulk_resource_list
    end
    get :media_thumbnail_remove
  end

  resources :organization_fields do
    collection do
      post :update_information
      post :update_index_template
      get :delete_field
      get :assignment_management
      post :create_custom_fields
      get :new_edit_custom_field
      get :index_fields_edit
    end
  end

  resources :collections do
    member do
      get 'edit/(:tab_type)', to: 'collections#edit', as: :edit_with_tab
      post :edit
      post :general_settings
      post :create_custom_fields
      get :new_edit_custom_field
      post :update_sort_fields
      get :delete_custom_meta_fields
      get :list_resources
      post :list_resources
      get :list_media
      post :list_media
      get 'collection_resources/new', to: 'collection_resources#new'
      post :import, to: 'collections#import'
      get :reset_default_tombstone_fields
    end
    collection do
      get '(/:collection_id)/export', to: 'collections#export', as: :export
      get :bulk_resource_list
      post :bulk_edit_operation
      get :fetch_bulk_edit_resource_list
      get :update_progress
      get :update_progress_files
      get :update_progress_transcripts
      get :update_progress_indexes
    end
    resources :collection_resources do
      get :add_resource_file
      post :save_resource_file
      put :update_file_name

app/models/playlist.rb
# Playlist
# Author::    Furqan Wasi  (mailto:furqan@weareavp.com)
#
# Aviary is an audiovisual content publishing platform with sophisticated features for search and permissions controls.
# Copyright (C) 2019 Audio Visual Preservation Solutions, Inc.
class Playlist < ApplicationRecord
  belongs_to :user
  belongs_to :organization
  validates_presence_of :name
  has_many :playlist_resources, dependent: :destroy
  has_many :playlist_items, dependent: :destroy
  has_attached_file :thumbnail, styles: { small: '450x230>', processors: %i[thumbnail compression] }, default_url: ''
  validates_attachment_content_type :thumbnail, content_type: %r[\Aimage\/.*\z]
  attribute :access, :integer
  enum access: %i[access_private access_public]
  scope :is_featured, -> { where(is_public: true, is_featured: true) }
  scope :is_featured_only, -> { where(is_featured: true) }
  scope :public_playlists, -> { where(access: 'access_public') }
  scope :order_feature_name, -> { order('is_featured DESC, lower(name) ASC') }
  before_save :process_fields
  def public?
    self.class.accesses[access.to_sym] == self.class.accesses[:access_public]
  end

  def process_fields
    self.description = description.strip_tags if description.present?
  end

  def private?
    self.class.accesses[access.to_sym] == self.class.accesses[:access_private]
  end

  def self.to_csv(current_organization)
    playlists = current_organization.playlists
    attributes = %w{Name Entries Featured Public}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      playlists.each do |c|
        is_feature = c.is_featured ? 'Yes' : 'No'
        is_public = c.public? ? 'Yes' : 'No'
        csv << [c.name, c.playlist_items_count, is_feature, is_public]
      end
    end
  end

  def self.fetch_list(page, per_page, query, organization_id, export = false)
    playlists = Playlist.joins(%i[organization]) if organization_id.present?
    playlists = playlists.where('playlists.organization_id = ? ', organization_id)
    if query.present?
      query = query.downcase.strip
      # featured status search
      status = true if 'yes'.include? query
      status = false if 'no'.include? query
      # public status search
      access_public_status = 1 if 'yes'.include? query
      access_public_status = 0 if 'no'.include? query
      query_string_name = 'playlists.name LIKE (?)'
      query_string_playlist_resources_count = query.is_i? ? 'playlists.playlist_resources_count = ? ' : ' "' + Time.now.to_i.to_s + '" = ? '
      query_string_organizations = 'organizations.id =?'
      playlists = if status.nil? && access_public_status.nil?
                    playlists.where("(#{query_string_name} OR #{query_string_playlist_resources_count}) AND #{query_string_organizations}", "%#{query}%", query, organization_id)
                  else
                    playlists.where("(#{query_string_name} OR #{query_string_playlist_resources_count} OR playlists.is_featured =? OR playlists.access = ?) AND #{query_string_organizations}", "%#{query}%",
                                    query, status, access_public_status, organization_id)
                  end
    end
    count = playlists.size
    playlists = playlists.limit(per_page).offset((page - 1) * per_page) unless export
    [playlists, count]
  end
end

app/helpers/playlist_helper.rb
# Playlist Helper
#
# Aviary is an audiovisual content publishing platform with sophisticated features for search and permissions controls.
# Copyright (C) 2019 Audio Visual Preservation Solutions, Inc.
module PlaylistHelper
  def set_playlist
    @playlist = Playlist.find_by(id: params[:playlist_id] || params[:id]) if params[:playlist_id] || params[:id]
    if @playlist.nil?
      flash[:error] = 'Playlist not found.'
      redirect_to root_path
    else
      @playlist
    end
  end

  def set_playlist_resource
    @playlist_resource = PlaylistResource.find_by(id: params[:playlist_resource_id] || params[:id]) if params[:playlist_resource_id] || params[:id]
  end

  def set_playlist_item
    @playlist_item = PlaylistResource.find_by(id: params[:playlist_item_id] || params[:id]) if params[:playlist_item_id] || params[:id]
  end

  def set_config
    @inside_playlist = true
    @playlist_controller = controller_name
    @playlist_action = action_name
  end

  def set_json_variables(msg = t('error_update'), status = :unprocessable_entity)
    @json_message = msg
    @json_status = status
  end

  def respond_with_json(message = nil, status = nil)
    respond_to do |format|
      format.json { render json: message || @json_message, status: status || @json_status }
    end
  end
end

app/views/playlists/_form.html.erb
<%= simple_form_for @playlist, :url => @playlist.new_record? ? playlists_path : playlist_path(@playlist), html: { novalidate: true } do |pl| %>
  <div class="row display-images border-0 py-0 px-3 my-0">
    <div class="col-md-6">
      <div class="form-group">
        <div class="field-title">
          <label for="banner">Playlist Thumbnail</label>
        </div>
        <div class="image-box">
          <div class="holder">
            <img id="banner" src="<%= @playlist.new_record? ? '#' : (image_url @playlist.thumbnail) %>" alt="">
          </div>
          <div class="file-upload">
            <%= pl.label @playlist.new_record? ? 'Add Image' : 'Upload new image', for: 'playlist_thumbnail' %>
            <%= pl.input :thumbnail, as: :file, error: false, label: false, input_html: { onchange: "readURL(this, 'banner');", accept: 'image/*' } %>
          </div>
        </div>
        <%= pl.error :thumbnail %>
      </div>
    </div>
  </div>

  <div class='row'>
    <div class="col-md-6">
      <div class="form-group">
        <div class="field-title">
          <label for="playlist-name">Playlist Name <button type="button" class="info-btn" data-content="What is your playlist's name?"></button></label>
        </div>
        <%= pl.input :name, label: false, input_html: { class: 'form-control playlist-name-field' } %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <div class="field-title">
          <label for="playlist_about">About Your Playlist <button type="button" class="info-btn" data-content="Tell users about your playlist."></button></label>
        </div>
        <%= pl.input :description, label: false, input_html: { class: 'form-control' } %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <div class="field-title">
          <%= pl.label 'Public ?', for: 'playlist_access' %>
        </div>
        <%= pl.select :access, [['Yes', 'access_public'], ['No', 'access_private']], required: true, label: false, class: 'custom-placeholder' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <div class="field-title">
          <%= pl.label 'Featured ?', for: 'pl._featured' %>
        </div>
        <%= pl.select :is_featured, [['Yes', true], ['No', false]], { prompt: 'Receive emails' }, required: true, label: false, class: 'custom-placeholder' %>
      </div>
    </div>
  </div>

  <div class='row'>
    <div class='col-md-6'>
      <div class='form-check'>
        <%= pl.input :is_audio_only, as: :boolean, label: "Render Media Player as Audio Player for Audio Files" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 text-right">
      <%= pl.submit @playlist.new_record? ? 'Save' : 'Update', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>
<br>
<script type="text/javascript">
    var playlist = new Playlist();
    document.addEventListener("DOMContentLoaded", function (event) {
        playlist.initialize();
    });
    $(function(e) {
        e.preventDefault;

        $('.info-btn').popover({
            html: true,
            trigger: "click",
            placement: "top"
        });

        $(document).on('click', function(e) {
            $('.info-btn').each(function() {
                if (!$(this).is(e.target) && $(this).has(e.target).length === 0 && $('.popover').has(e.target).length === 0) {
                    $(this).popover('hide');
                }
            });
        });

        $(document).ready(function(){
            $('.form-check label').append('<span class="icon-check"></span>')
        })
    });
</script>

app/views/playlists/_list_playlist_items.html.erb
<% if @playlist_resources.length > 0 %>
  <% @playlist_resources.each do |pl_rsrc| %>
    <% collection_resource_playlsit = pl_rsrc.collection_resource %>
    <% can_access = (can? :read, collection_resource_playlsit) || collection_resource_playlsit.can_view || collection_resource_playlsit.can_edit || (can? :edit, collection_resource_playlsit.collection.organization) %>

    <div id='playlist_resource_<%= pl_rsrc.id %>' data-id="<%= pl_rsrc.id %>" class="box <%= pl_rsrc == @playlist_resource ? 'now-playing' : 'not-playing' %> playlist_resource_single <%= can_access ? 'canplay' : ' locked ' %>  <%= pl_rsrc != @playlist_resource && !can_access ? 'p-5-0-5-0px' : ' ' %>">
      <% if !@playlist_show.present? && !@playlist_show && (can? :manage, @playlist) %>
        <div class="form-group no-field plr-sort-container m-0">
          <input type="checkbox" data-bulk_edit_playlist_resource_id="<%= pl_rsrc.id %>" data-bulk_edit_resource_id="<%= pl_rsrc.collection_resource_id %>" class="choose-resource">
          <span class="sort-icon"><i class="fa fa-ellipsis-v"></i></span>
          <input type="text" value='<%= pl_rsrc.sort_order %>' disabled='disabled' class="form-control plr-sort-index position-relative only_allow_number" style="z-index: 9" data-id='<%= pl_rsrc.id %>' name="playlist_resource_sort[<%= pl_rsrc.id %>]">
        </div>
      <% end %>
      <% unless @playlist_show.present? && @playlist_show %>
        <% playlist_link = (pl_rsrc == @playlist_resource) ? 'javascript:void(0)' : playlist_edit_path(@playlist, playlist_resource_id: pl_rsrc.id) %>
      <% else %>
        <%
          param_link = { playlist_id: @playlist.id, playlist_resource_id: pl_rsrc.id }
          param_link[:playlist_id] = @playlist.id
          param_link[:embed] = true if params[:embed].present?
          param_link[:media_player] = true if params[:media_player].present?
          param_link[:share] = params[:share] if params[:share].present?
          param_link[:access] = params[:access] if params[:access].present?
          playlist_link = (pl_rsrc == @playlist_resource) ? 'javascript:void(0)' : playlist_show_path(param_link) %>
      <% end %>

      <% unless can_access %>
        <div class="access_hold feat-reso-locked">
          <div class="holder">
            <div class="box">
              <div class="col-12">
                <div class="col-12 mt-2 d-inline-block">
                  <%= lock_image('h-20px') %>

                </div>
                <div class="col-12 mt-1">
                  <div class="access_request_text_custom text-white">You don't have access.</div>

                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>


      <div class="text">
        <a href="<%= playlist_link %>" class="image">
          <% thumb_url = nil %>
          <% if pl_rsrc.playlist_items.present? %>
            <% if pl_rsrc.playlist_items.first.collection_resource_file.present? %>
              <% thumb_url = pl_rsrc.playlist_items.first.collection_resource_file.thumbnail.url if pl_rsrc.playlist_items.first.try(:collection_resource_file) %>
              <% if thumb_url.blank? && pl_rsrc.playlist_items.first.try(:collection_resource_file) %>
                <% present(pl_rsrc.playlist_items.first.collection_resource_file) do |presenter| %>
                  <% thumb_url = presenter.media_type.include?('avalon') || presenter.media_type.include?('video') ? "https://#{ENV['S3_HOST_CDN']}/public/images/video-default.png" : "https://#{ENV['S3_HOST_CDN']}/public/images/audio-default.png" %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
          <% thumb_url = "https://#{ENV['S3_HOST_CDN']}/public/images/video-default.png" if thumb_url.blank? %>
          <%= image_tag(thumb_url) %>
        </a>

        <div class="title_description">
          <% if !@playlist_show.present? && !@playlist_show && (can? :manage, @playlist) %>

            <span style="font-size: 16px;font-weight: bold;color: #000;text-decoration: none;line-height: 1.25;" data-bip-type="input" data-bip-ok_button="title" data-bip-attribute="title" data-bip-activator="#button_id_<%=pl_rsrc.id %>" data-bip-object="playlist_resource" data-bip-original-content="<%= pl_rsrc.name %>"
                  data-bip-skip-blur="false" data-bip-url="<%= update_description_playlist_playlist_resource_path(playlist_id: pl_rsrc.playlist_id, id: pl_rsrc.id) %>" data-bip-value="<%= pl_rsrc.name %>"
                  class="best_in_place cursor-pointer" onclick="window.location='<%= playlist_link %>'" id="best_in_place_pl_resource_2_title_<%=pl_rsrc.id %>" method="PUT">  <%= pl_rsrc.name %>
            </span>
            <i class="ml-1 mt-1 fa fa-pencil cursor-pointer edit-description-resource" data-toggle="tooltip" data-placement="top" title="Click to edit the title."  id="button_id_<%=pl_rsrc.id %>"></i>

          <% else %>
            <a href="<%= playlist_link %>" class='title <%= can_access ? 'can-play-resource' : ' ' %>'> <%= pl_rsrc.name %> </a>
          <% end %>
        </div>
        <div class="coll-name">
          <div class="ico">
            <% icon_src = (pl_rsrc.collection_resource.collection.present? && pl_rsrc.collection_resource.collection.favicon.present?) ? pl_rsrc.collection_resource.collection.favicon.url(:small) : image_url('collection_folder_icon.svg') %>
            <img src="<%= icon_src %>" alt="collection">
          </div>
          <!--          collection_url(pl_rsrc.collection_resource.collection, host: Utilities::AviaryDomainHandler.subdomain_handler(pl_rsrc.collection_resource.collection.organization))-->
          <%= link_to pl_rsrc.collection_resource.collection.title, playlist_link, class: "text" %>
        </div>



        <div class="playlist_description_full playlist_resource_description float-left playlist_resource_description_<%= pl_rsrc.id %>">
          <div class="less-description d-inline">
            <%= pl_rsrc.description.strip_tags %>
          </div>
          <div class="d-none full-description">
            <%= Sanitize.fragment(pl_rsrc.description, :elements => ['p', 'br']).html_safe %>
          </div>

        </div>
        <% unless @playlist_show.present? && @playlist_show && (can? :manage, @playlist) %>
          <button class="text-primary edit_description_playlist badge badge-primary" data-toggle="modal" data-target="#edit_playlist_resource_description_modal_center" data-playlist_resource_id='<%= pl_rsrc.id %>' data-url="<%= update_description_playlist_playlist_resource_path(playlist_id: pl_rsrc.playlist_id, id: pl_rsrc.id) %>">
            Edit Description
          </button>
          <%= link_to "Remove".html_safe, playlist_playlist_resource_url(pl_rsrc, playlist_id: @playlist.id), method: :delete, data: { confirm: 'Are you sure you want to delete this Resource from Playlist?' }, class: ' badge badge-danger remove_playlist_resoure' %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/playlists/_single_playlist.html.erb
<div class="card" id="single_playlist_container" style="border: none;">
  <div class="card-header py-2 pl-3 pr-2 bg-white border" id="heading<%= playlist.id %>">
    <h2 class="mb-0">
      <span class="cursor-pointer d-flex align-items-center collapsed" data-toggle="collapse" data-target="#collapse<%= playlist.id %>" aria-expanded="false" aria-controls="collapsec<%= playlist.id %>">
        <div><%= image_tag(playlist.thumbnail.present? ? playlist.thumbnail.url(:small) : image_path('playlist_add.png'), class: 'mt-2 mr-2 w-20px h-20px') %></div>
        <strong data-toggle="tooltip" title="<%= playlist.name %>">
          <%= link_to(playlist.name, playlist_show_path(playlist), class: 'playlist_title') %>
          <% if collection_resource_playlist_ids.include?(playlist.id) %>
            <%= image_tag(image_path('already_part_of_playlsit.png'), class: 'float-right mt-1') %>
          <% end %>
        </strong>
        <% if current_user_is_org_user?(organization) && from_action == 'listing_for_add_to_playlist' %>
            <a href="javascript:void(0);" class="add_resource_to_playlist d-flex btn btn-light text-dark ml-auto align-items-center" data-url="<%= playlist_add_to_resource_url(playlist_id: playlist.id, collection_resource_id: collection_resource.id) %>"
               data-playlistid="<%= playlist.id %>" data-resourceid="<%= collection_resource.id %>">
              Add
              <div id="playlist_loader_<%= playlist.id %>" class="ml-1 playlist_loader d-none float-left">
                <div class="img">
                  <div class="hold">
                    <%= image_tag("https://#{ENV['S3_HOST_CDN']}/public/images/ajax-loader.gif", class: 'mt-1 h-20px') %>
                  </div>
                </div>
              </div>
            </a>

          <% if playlist.try(:playlist_resources).present? && !playlist.playlist_resources.size.zero? %>
            <a href="<%= playlist_edit_path(playlist.id) %>" class="add_resource_to_playlist_specific btn btn-light text-dark ml-2 align-items-center">
              Select specific media files
            </a>
          <% else %>
            <span  class="add_resource_to_playlist_specific add_resource_to_playlist_specific_disabled btn btn-sm ml-1 align-items-center text-primary">
              <i class="fa fa-plus mr-1"></i>Select specific media files
            </span>
          <% end %>
        <% end %>
      </span>
    </h2>
  </div>
</div>

app/views/playlists/index.html.erb
<div id="main_container" class="container-fluid">
  <div class="main_contain">
    <main>
      <div class="text-headline jumbotron">
        <div class="heading-holder table-head">
          <div class="row">
            <div class="col-md-6"><h1>Playlists</h1></div>
            <div class="col-md-6">
              <%= link_to 'Add Playlist', new_playlist_path, class: 'btn btn-primary btn-xs pull-right' %>
              <%= link_to 'Export to CSV', playlist_export_path, class: 'btn btn-outline-primary btn-xs pull-right mr-2' %>
            </div>
          </div>
        </div>
      </div>
      <div class="data-table playlists-datatable">
        <div>
          <%= content_tag :table, role: :datatable, class: ["table", "table-striped", 'table-bordered'], id: 'playlist_data_table', data: { url: playlists_path(format: :json)} do %>
            <thead>
            <tr>
              <th>Name</th>
              <th>Entries</th>
              <th>Featured</th>
              <th>Public</th>
              <th>Action</th>
            </tr>
            </thead>
            <tbody>
            </tbody>
          <% end %>
        </div>
      </div>
    </main>
  </div>
</div>
<script type="text/javascript">
    var playlist = new Playlist();
    document.addEventListener("DOMContentLoaded", function (event) {
        playlist.initialize();
    });
</script>