config/routes.rb
Rails.application.routes.draw do
  resources :saved_searches, except: [:index] do
    collection do
      match :datatable, to: 'saved_searches#index', via: %i[get post]
    end
  end
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  concern :searchable, Blacklight::Routes::Searchable.new
  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog', constraints: { format: 'html' } do
    concerns :searchable
    concerns :range_searchable
    collection do
      post :update_selected_playlist
      post :assign_to_playlist
      post :assign_resources_to_list
    end
  end
  devise_for :admins
  root 'home#index'
  get '/collection', to: 'catalog#index', as: :org_collection, constraints: RestrictJsonRequest.new
  get '/playlist', to: 'home#index', as: :org_playlist
  get '/aboutus', to: 'home#index', as: :org_aboutus
  get '/robots.:format' => 'home#robots', constraints: { format: /(txt)/ }
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    invitations: 'users/invitations',
    confirmations: 'users/confirmations'
  }
  devise_scope :user do
    get '/profile', to: 'devise/registrations#edit'
  end
  post '/update_resource_column_sort/:id', to: 'organizations#update_resource_column_sort', as: 'update_resource_column_sort'
  post '/update_resource_file_column/:id', to: 'organizations#update_resource_file_column', as: 'update_resource_file_column'
  get 'forbidden', to: 'home#forbidden', as: :forbidden
  get 'notfound', to: 'home#not_found', as: :not_found
  get 'get_collections', to: 'home#featured_collections', as: :get_collections
  get 'get_playlists', to: 'home#featured_playlists', as: :get_playlists
  get 'get_resources', to: 'home#featured_resources', as: :get_resources
  get 'get_organization', to: 'home#featured_organization', as: :get_organization
  get 'record_tracking', to: 'home#record_tracking', as: :record_tracking
  get 'get_collectionwise_resources/:id', to: 'home#collection_wise_resources', as: :get_collectionwise_resources
  get 'users/add_member_row', to: 'users#add_member_row', as: :add_member_row

  namespace :admin do
    resources :users, except: %i[show] do
      put '/organization', to: 'users#organization_update'
      delete '/organization/:org_user_id', to: 'users#organization_destory', as: :organization_delete
      post '/organization', to: 'users#organization_create'

      collection do
        get '/pending', to: 'users#pending'
        get '/export_users', to: 'users#export'
      end
    end

    get '/', to: 'users#index'
  end
  get 'ohms_records', to: 'interviews/managers#index', as: :ohms_records
  get 'ohms_records/collection/ohms_records/user_assignments/:interview_id/:user_id', to: 'interviews/managers#ohms_assignments', as: :ohms_collection_records_user_assignments
  get 'my_ohms_assignment', to: 'interviews/managers#index', as: :my_ohms_assignment
  post 'my_assignment_listing', to: 'interviews/managers#listing', as: :my_assignment_listing
  post 'ohms_records', to: 'interviews/managers#create', as: :ohms_records_create
  get 'ohms_records/:id/edit', to: 'interviews/managers#edit', as: :ohms_records_edit
  get 'ohms_records/new', to: 'interviews/managers#new', as: :ohms_records_new
  get 'ohms_records/ohms_index/:id', to: 'interviews/interview_index#show', as: :ohms_index
  get 'ohms_records/ohms_index/:id/edit', to: 'interviews/interview_index#edit', as: :ohms_index_edit
  get 'ohms_records/ohms_index/new/:id', to: 'interviews/interview_index#new', as: :ohms_index_new
  get 'ohms_records/user_assignments/:interview_id/:user_id', to: 'interviews/managers#ohms_assignments', as: :ohms_records_user_assignments

  get 'ohms_configuration', to: 'interviews/managers#ohms_configuration', as: :ohms_configuration
  post 'ohms_configuration', to: 'interviews/managers#ohms_configuration_update', as: :ohms_configuration_update
  get 'ohms_records/collections', to: 'interviews/collections#index', as: :list_collections
  post 'ohms_records/collections/listing', to: 'interviews/collections#listing', as: :listing_collections

  get 'ohms_records/collection/:collection_id', to: 'interviews/collections#interviews', as: :interview_list_of_collections
  post 'ohms_records/collection/:collection_id', to: 'interviews/collections#interviews_list', as: :interview_lists_of_collections
  get 'ohms_records/collection/export/:collection_id', to: 'interviews/collections#export', as: :interview_export

  namespace :interviews do
    resources :managers do
      collection do
        post :import_metadata_xml
        post :update_column_info
        post :listing
        match :bulk_resource_list, via: %i[get post]
        post :bulk_interview_edit
      end
      member do
        get 'export.:format', to: 'managers#export', as: :export
        get 'preview', to: 'managers#preview', as: :preview
        match :sync, via: %i[get post patch]
      end
    end
    resources :transcripts, only: %i[index] do
      member do
        get 'change_sync_interval', to: 'transcripts#change_sync_interval', as: 'change_sync_interval'
        match :create, via: %i[get post]
      end
    end

    get 'interview/notes/:id.:format', to: 'notes#index', as: :list_notes
    post 'interview/notes/:id.:format', to: 'notes#create', as: :create_note
    post 'interview/note/update/:id.:format', to: 'notes#update', as: :update_note
    post 'interview/note/delete', to: 'notes#delete', as: :delete_note
    get 'ohms_interview/notes/export/:id.:format', to: 'notes#export', as: :ohms_export_note

    resources :interview_index
    get 'interview/index/new/:id', to: 'interview_index#new', as: :interview_index_new
    post 'interview/index/create/:id', to: 'interview_index#create', as: :interview_index_create
    post 'interview/index/status/:id', to: 'interview_index#status_update', as: :interview_index_status_update
    post 'interview/index/update_template/:id', to: 'interview_index#update_template', as: :interview_update_template
    get 'interview/index/index_segment_timeline/:id', to: 'interview_index#index_segment_timeline', as: :index_segment_timeline
  end

  namespace :thesaurus do
    resources :manager do
      get :export
      collection do
        match :autocomplete, via: %i[get post]
        match :assignment_management, via: %i[get post]
        match :datatable, via: %i[get post]
      end
    end
  end

  resources :users, only: %i[destroy index] do
    post '/add_new_member', to: 'users#add_new_member', as: :add_new_member
    post '/change_org_status', to: 'users#change_org_status', as: :change_org_status
    post '/change_org_role', to: 'users#change_org_role', as: :change_org_role
    get '/remove_user(/:organization_id)', to: 'users#remove_user', as: :remove_user
  end

  get 'pricing', to: 'home#pricing', as: :pricing
  get 'terms_of_service', to: 'home#terms_of_service', as: :terms_of_service
  get 'privacy_policy', to: 'home#privacy_policy', as: :privacy_policy
  # get 'contact_us', to: 'home#contact_us', as: :contact_us
  # get 'support', to: 'home#support', as: :support
  get 'about', to: 'home#about', as: :about
  get 'features', to: 'home#features', as: :features
  get 'security', to: 'home#security', as: :security
  post 'submit_request', to: 'home#submit_request', as: :submit_request
  resources :organizations, only: %i[index show update]
  get '/organization_profile', to: 'organizations#edit', as: :edit_organization
  get '/display_settings', to: 'organizations#display_settings', as: :display_settings_organization
  get :color_contrast, to: 'organizations#color_contrast', as: :color_contrast_organization
  match '/search_configuration', to: 'organizations#search_configuration', as: :search_configuration_organization, via: %i[get post]
  post '/set_layout', to: 'home#set_layout'
  scope :public_access_urls do
    match 'index', to: 'public_access_urls#index', as: 'public_access_urls', via: %i[get post]
    match 'update_info', to: 'public_access_urls#update_info', as: 'public_access_urls_update_info', via: %i[get post]
    get 'edit/:id', to: 'public_access_urls#edit', as: 'public_access_urls_edit'
    post 'update/:id', to: 'public_access_urls#update', as: 'public_access_urls_update'
  end
  resources :collection_resource_files do
    collection do
      post :data_table, to: 'collection_resource_files#index'
      post :bulk_resource_file_edit
      get :export_resource_file
      get :bulk_resource_list
    end
    get :media_thumbnail_remove
  end

  resources :organization_fields do
    collection do
      post :update_information
      post :update_index_template
      get :delete_field
      get :assignment_management
      post :create_custom_fields
      get :new_edit_custom_field
      get :index_fields_edit
    end
  end

  resources :collections do
    member do
      get 'edit/(:tab_type)', to: 'collections#edit', as: :edit_with_tab
      post :edit
      post :general_settings
      post :create_custom_fields
      get :new_edit_custom_field
      post :update_sort_fields
      get :delete_custom_meta_fields
      get :list_resources
      post :list_resources
      get :list_media
      post :list_media
      get 'collection_resources/new', to: 'collection_resources#new'
      post :import, to: 'collections#import'
      get :reset_default_tombstone_fields
    end
    collection do
      get '(/:collection_id)/export', to: 'collections#export', as: :export
      get :bulk_resource_list
      post :bulk_edit_operation
      get :fetch_bulk_edit_resource_list
      get :update_progress
      get :update_progress_files
      get :update_progress_transcripts
      get :update_progress_indexes
    end
    resources :collection_resources do
      get :add_resource_file
      post :save_resource_file
      put :update_file_name

app/models/interviews/interview_note.rb
# Interviews
#
# Aviary is an audiovisual content publishing platform with sophisticated features for search and permissions controls.
# Copyright (C) 2019 Audio Visual Preservation Solutions, Inc.
module Interviews
  # Interview Note
  class InterviewNote < ApplicationRecord
    include UserTrackable
    belongs_to :interview
    validates_length_of :note, maximum: 1000, allow_blank: false
  end
end

app/controllers/interviews/collections_controller.rb
# frozen_string_literal: true

#
# Aviary is an audiovisual content publishing platform with sophisticated features for search and permissions controls.
# Copyright (C) 2019 Audio Visual Preservation Solutions, Inc.
module Interviews
  # CollectionsController
  class CollectionsController < ApplicationController
    before_action :authenticate_user!
    # GET /interview/collections
    # GET /interview/collections.json
    def index
      authorize! :manage, current_organization
      session[:interview_bulk] = [] unless request.xhr?
      @interviews = Interviews::Interview.all
      @search_columns = current_organization.interview_search_column
      @display_columns = current_organization.interview_display_column
      @collections = Collection.where(organization_id: current_organization.id)
      @users = current_organization.organization_ohms_assigned_users
    end

    def listing
      authorize! :manage, current_organization
      respond_to do |format|
        format.html
        format.json { render json: Datatables::InterviewsCollectionsDatatable.new(view_context, current_organization) }
      end
    end

    def interviews
      authorize! :manage, current_organization
      session[:interview_bulk] = [] unless request.xhr?
      @interviews = Interviews::Interview.fetch_interview_list(1, 10_000_000, [], '', { collection_id: params['collection_id'] }, {}, export: false, current_organization: current_organization)
      @search_columns = current_organization.interview_search_column
      @display_columns = current_organization.interview_display_column
      @collections = Collection.where(organization_id: current_organization.id)
      @users = current_organization.organization_ohms_assigned_users
      @collection_id = ''
      @series_id = ''
      @collection_title = ''
      @series_title = ''
      records = @interviews.try(:first)
      records.each do |record|
        @collection_id = record['collection_id_ss'] if @collection_id.blank?
        @series_id = record['series_id_ss'] if @series_id.blank?
        @collection_title = record['collection_name_ss'] if @collection_title.blank?
        @series_title = record['series_ss'] if @series_title.blank?
        if @series_title.present? && @collection_title.present? && @series_id.present? && @collection_id.present?
          break
        end
      end
      render 'interviews/managers/index'
    end

    def interviews_list
      authorize! :manage, current_organization
      organization_user = OrganizationUser.find_by(user_id: current_user.id)

      respond_to do |format|
        format.html
        format.json { render json: Datatables::InterviewsDatatable.new(view_context, current_organization, '', organization_user) }
      end
    end

    def export
      authorize! :manage, current_organization
      if params[:collection_id].present?
        InterviewBulkExportWorker.perform_in(1.second, params[:collection_id], current_user.id, current_organization.id)
      end
      redirect_to list_collections_path, notice: 'OHMS Interview XMLs are in progress and will be exported shortly. You will be notified via email once the export is complete. You do not need to stay on this page.'
    end
  end
end

app/helpers/interviews_helper.rb
# Interviews Helper
#
# Aviary is an audiovisual content publishing platform with sophisticated features for search and permissions controls.
# Copyright (C) 2019 Audio Visual Preservation Solutions, Inc.
module InterviewsHelper
  def self.display_field_title_interview(field)
    case field.to_s
    when 'id_is', 'id_ss'
      'ID'
    when 'title_accession_number_ss'
      'Title | Accession Number'
    when 'collection_id_ss'
      'Collection ID'
    when 'series_id_ss'
      'Series ID'
    when 'date_non_preferred_format'
      'Date (non-preferred format)'
    when 'collection_name'
      'Collection Name'
    when 'thesaurus_keywords'
      'Thesaurus (Keywords)'
    when 'thesaurus_subjects'
      'Thesaurus (Subjects)'
    when 'thesaurus_titles'
      'Thesaurus (Titles)'
    when 'miscellaneous_cms_record_id'
      'CMS Record ID'
    when 'miscellaneous_ohms_xml_filename'
      'OHMS XML Filename'
    when 'miscellaneous_use_restrictions'
      'Use Restrictions'
    when 'miscellaneous_use_restrictions_bs'
      'Use Restrictions'
    when 'miscellaneous_sync_url'
      'Alt Sync URL (Legacy Field)'
    when 'miscellaneous_user_notes'
      'User Notes'
    when 'media_url_texts'
      'Media URL'
    when 'ohms_assigned_user_id_is'
      'Assignments'
    else
      field.to_s.sub('_ss', '').sub('_sms', '').sub('_texts', '').sub('_text', '').sub('_is', '').sub('_bs', '').titleize
    end
  end

  def to_hms(time)
    Time.at(time).utc.strftime('%H:%M:%S')
  rescue StandardError => ex
    Rails.logger.error ex.message
    '00:00:00'
  end

  def hms_to_number(hms)
    hms.split(':').map(&:to_i).inject(0) { |a, b| a * 60 + b }
  rescue StandardError => ex
    Rails.logger.error ex.message
    0
  end

  def export_csv(interview_id)
    interviews = Interviews::Interview.where(id: interview_id)
    csv_rows = []
    key = 0
    csv_rows << ['Sn#', 'OHMS Record Title', 'Interviewee', 'Accession Number', 'Interview Date', 'Collection ID', 'Collection Name', 'Note Content', 'Note Status', 'Export Date']
    interviews.each do |interview|
      interview.interview_notes.each do |note|
        key += 1
        row = []
        row << key
        row << interview.title
        row << interview.interviewee.join(';;')
        row << interview.accession_number
        row << interview.interview_date
        row << interview.collection_id
        row << interview.collection_name
        row << note['note']
        row << (note['status'] ? 'resolved' : 'unresolved')
        row << DateTime.now.strftime('%Y-%m-%d').to_s
        csv_rows << row
      end
    end
    csv_rows
  end

  def ends_with_punctuation?(line)
    line.strip =~ %r{[!"#.$&'*+\-/<=>?@^_`{|}~]\z} ? true : false
  end

  def fix_line_breaks(transcript)
    processed_transcript = ''
    transcript.split("\n").each { |line| processed_transcript += "#{line}#{line.present? && ends_with_punctuation?(line) ? "\n" : ''}" }
    processed_transcript
  end
end

app/views/interviews/interview_index/_index_template.html.erb
<div class="form-check mr-2 ml-2">
  <label class="form-check-label">
    <input type="checkbox" id="index_default_template" name="index_default_template" class="form-check-input" value="1" <%=(@file_index.index_default_template.positive? ? 'checked': '') %> >Set as default
  </label>
</div>
<select class="custom-placeholder dont-apply-selectize" id='index_template' name='index_template'>
  <option value="">Select option</option>
  <%index_template_items().each_with_index do |index,key| %>
    <option value="<%=key%>" <%=(@file_index.index_template == key ? 'selected' : '')%>><%=index['name']%></option>
  <%end%>
</select>
<a class="btn btn-outline-secondary collection-custom-field-icon ml-2 index_template_btn" data-url="<%=interviews_interview_update_template_url(@file_index.id)%>" href="javascript:void(0);">
  <i class="fa fa-save"></i>
</a>

app/views/interviews/interview_index/_media_timeline.html.erb
<% if index_points.present? && index_points.length > 0 %>
  <div class="flex media-timeline my-2">
    <div id="media-index-timeline-pointer" class="media-index-timeline"></div>
    <div id="media-index-timeline-div" class="d-flex" style="gap: 1px; height: 20px;">
      <%== render_index_timeline(total_duration, index_points, active_point_id) %>
    </div>
  </div>
<% end %>

app/views/interviews/interview_index/_status.html.erb
<% if @interview.present? %>
  <select class="custom-placeholder dont-apply-selectize form-control ml-2 mr-3 index_status_select" name="index_status" data-url="<%= interviews_interview_index_status_update_path(@interview.id) %>">
    <% @interview.listing_metadata_index_status.each do |row| %>
      <option value="<%= row[0] %>" <%= row[0] == @interview.try(:index_status).to_s ? "selected" : "" %> ><%= row[1] %></option>
    <% end %>
  </select>
<% end %>

app/views/interviews/interview_index/_top.html.erb
<%if @interview.present? %>
  <% if @interview.media_url.empty? && @interview.embed_code.empty? && @interview.media_host_item_id.empty? %>
  <div class="no-media">
    <% if params[:action] == "show" || params[:action] == "show_index" %>
    <div id="noAudio">
      There is no online media associated with this item. Please update the media settings in the <a href="<%= ohms_records_edit_path(@interview.id) %>">metadata editor</a> or proceed to index this item using offline media.
    </div>
    <% else %>
    <div id="noMediaConnection">No Media Connection</div>
    <% end %>
  </div>
  <% else %>
  <% video_info = interview_video_info(@interview) %>
  <div id="media_host" data-host="<%= @interview.media_host %>">
    <% if @interview.media_host == 'Kaltura' %>
      <div id="player_section" class="player-section video-placeholder">
        <div class="video-hold" oncontextmenu="return false;">
          <div id="kaltura_player_embed"></div>
          <script src="<%= video_info['kaltura_url'] %>/p/<%= video_info['partner_id'] %>/sp/<%= video_info['partner_id'] %>00/embedIframeJs/uiconf_id/<%= video_info['uiconf_id'] %>/partner_id/<%= video_info['partner_id'] %>"></script>
          <script>
              let interviewTranscriptManagerKaltura = new InterviewTranscriptManager()
              interviewTranscriptManagerKaltura.audioBegin = new Audio("<%= root_url %>/sounds/site_swf_startBeep.mp3");
              interviewTranscriptManagerKaltura.audioEnd = new Audio("<%= root_url %>/sounds/site_swf_midBeep.mp3");
              kWidget.embed({
                  'targetId': 'kaltura_player_embed',
                  'wid': '_<%= video_info['partner_id'] %>',
                  'uiconf_id': '<%= video_info['uiconf_id'] %>',
                  'entry_id': '<%= video_info['entry_id'] %>',
                  'flashvars':
                          {
                              'autoPlay': false,
                              'externalInterfaceDisabled': false
                          },
                  'params':
                          {
                              'wmode': 'transparent'
                          },
                  readyCallback: function (playerId) {
                      window.kdp = document.getElementById(playerId);
                      setInterval( function () {
                        if(!$('.largePlayBtnBorder').is(":visible")){
                          interviewTranscriptManagerKaltura.kalturaManager(kdp);
                        } else {
                          interviewTranscriptManagerKaltura.audioBegin.pause();
                        }
                      }, 900);
                  }
              });
          </script>

        </div>
      </div>
    <% elsif @interview.media_host == 'SoundCloud' %>
      <div id="player_section" class="player-section video-placeholder">
        <div class="video-hold" oncontextmenu="return false;">
          <%= video_info['iframe'].html_safe %>
          <script src="https://w.soundcloud.com/player/api.js"></script>
        </div>
      </div>

    <% elsif @interview.media_host == 'Brightcove' %>
      <video
      class="video-js" controls playsinline preload="auto"  style="width: 100%;" data-cast-title="<%= @interview.title %>"
      id="player"
      data-account="<%= video_info['account'] %>" 
      data-player="<%= video_info['player'] %>" 
      data-embed="default" 
      data-video-id="<%= video_info['video_id'] %>" 

      ></video>
      <script src="https://players.brightcove.net/<%= video_info['account'] %>/<%= video_info['player'] %>_default/index.min.js"></script>

    <% elsif @interview.media_host == 'Vimeo' %>
      <% if video_info['error'].present? %>
        <div class="no-media">
          <div id="noAudio" class="text-center" style="height: auto;"><%= video_info['error'] %></div>
        </div>
      <% else %>
        <div id="player_section" class="video-placeholder">
          <%== video_info['src'] %>
          <div class="title">
            <strong><%= @interview.title %></strong>
          </div>
        </div>
      <% end %>
    <% elsif @interview.media_format.include?("video") %>
      <% if video_info['error'].present? %>
        <div class="no-media">
          <div id="noAudio" class="text-center" style="height: auto;"><%= video_info['error'] %></div>
        </div>
      <% else %>
        <div id="player_section" class="player-section video-placeholder">
          <div class="video-hold" oncontextmenu="return false;">
            <video id="player" class="video-js" controls playsinline preload="auto"  style="width: 100%;"
              data-cast-title="<%= @interview.title %>" client_id="<%= video_info['client_id'] %>" >
              <% if video_info['source_tags'].present? %>
                <%= video_info['source_tags'].html_safe %>
              <% else %>
                <source src="<%= video_info['src'] %>" type="<%= video_info['type'] %>" />
              <% end %>
            </video>
          </div>
          <div class="title">
            <strong><%= @interview.title %></strong>
          </div>
        </div>
      <% end %>

    <% else %>
      <div class="player-section video-placeholder audio audio-player" id="player_section" oncontextmenu="return false;">
        <div class="audio">
          <audio id="player" class="video-js" controls playsinline preload="auto">
          <% if video_info['source_tags'].present? %>
              <%= video_info['source_tags'].html_safe %>
            <% else %>
              <source src="<%= video_info['src'] %>" type="<%= video_info['type'] %>" />
            <% end %>
          </audio>
        </div>
      </div>
    <% end %>

    <% if select_file_index_points(@file_index_points, @file_index_point).length > 0 %>
      <div id="index-segments-timeline" data-active-point-id="<%= params[:action] == 'edit' ? params[:id] : '' %>"
        data-url="<%= interviews_index_segment_timeline_path(@interview&.file_indexes&.first&.id)%>"></div>
    <% end %>

  </div>
  <% end %>
  <% if params[:action] == "show" || params[:action] == "show_index"  %>
    <%= link_to 'Add Index Segment', 'javascript://', class: 'btn btn-outline-dark btn-block pull-left add_tag', data: { url: ohms_index_new_path } %>
  <% end %>
<% else %>
  <div id="media_host" data-host="" style="width: 75%;" >
    <% is_audio_only = @collection_resource.present? ? @collection_resource.collection.is_audio_only : false %>
    <%= render partial: 'collection_resources/show/mediaplayer', locals: { single_file: @resource_file, is_audio_only: is_audio_only } %>

    <% if select_file_index_points(@file_index_points, @file_index_point).length > 0 %>
      <div id="index-segments-timeline" data-active-point-id="<%= params[:action] == 'edit' ? params[:id] : '' %>"
        data-url="<%= interviews_index_segment_timeline_path(@interview&.file_indexes&.first&.id)%>"></div>
    <% end %>
    <% if params[:action] == "show" || params[:action] == "show_index"  %>
      <% if @file_index.present? %>
        <%= link_to 'Add Index Segment', 'javascript://', class: 'btn btn-primary btn-xs pull-left mt-2 add_tag', data: { url: add_index_file_path(@resource_file.id, @file_index.id) } %>
      <% else %>
        <%= link_to 'Add Index Segment', 'javascript://', class: 'btn btn-primary btn-xs pull-left mt-2 add_tag', data: { url: add_index_path(@resource_file.id) } %>
      <% end %>
    <% end %>
  </div>
<% end %>
<style>
  .vjs-has-started .vjs-control-bar {
      display: flex !important;
      visibility: visible !important;
      opacity: 1 !important;
  }
</style>
<script src="https://player.vimeo.com/api/player.js"></script>

app/views/interviews/interview_index/edit.html.erb
<div id="main_container" class="container-fluid">
  <div class="main_contain">
    <main>
      <%= render 'interviews/interview_index/form' %> 
    </main>
  </div>
</div>
<%= render 'interviews/managers/notes' %>
<script type="text/javascript">
    let interviews_index_manager = new InterviewIndexManager(
      parseInt('<%= @forward_duration %>', 10), parseInt('<%= @backward_duration %>', 10), '<%= update_skip_duration_indexes_url %>'
    );
    $(function () {
      interviews_index_manager.initialize();
    });
</script>

app/views/interviews/interview_index/new.html.erb
<div id="main_container" class="container-fluid">
  <div class="main_contain">
    <main>
      <%= render 'interviews/interview_index/form' %> 
    </main>
  </div>
</div>
<%= render 'interviews/managers/notes' %>
<script type="text/javascript">
    let interviews_index_manager = new InterviewIndexManager();
    $(function () {
      interviews_index_manager.initialize();
    });
</script>